// ABT #1220: OpenMagnetics::Bobbin::create_quick_bobbin can synthesise pins, off by default.
//
// Every expected number below is a hand computation from src/data/quick_bobbin_pins.json (the
// medians over distinct catalogue footprints, generated by scripts/derive_quick_bobbin_pins.py):
//   E-type  pitch 2.54 mm below a 13.825 mm core width, 3.81 mm up to 17.85 mm, 5.08 mm from there;
//           edge margin 2.00 mm; vertical row clearance 4.70 mm, horizontal 1.55 mm
//   PQ      pitch 2.54 / 2.54 (grid) / 3.81 / 5.08 mm split at 20.55, 23.55 and 29.25 mm; edge
//           margin 2.03 mm; vertical row clearance 3.72 mm; no horizontal former
//   all     grid 2.54 mm, pin 0.91 mm x 6.35 mm, rail standoff 2.372 mm, at least 2 pins a row;
//           rail walls around a row (ABT #1249): outer 1.325 mm, inner 2.83 mm, end 1.467 mm
// and the nominal core dimensions MKF reads (width A, height 2B, depth C, window height 2D).

#include <source_location>
#include "constructive_models/Bobbin.h"
#include "constructive_models/Coil.h"
#include "constructive_models/Core.h"
#include "constructive_models/Magnetic.h"
#include "support/Settings.h"
#include "support/Utils.h"
#include "TestingUtils.h"

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <cstdlib>
#include <filesystem>
#include <set>
#include <tuple>

using namespace MAS;
using namespace OpenMagnetics;

namespace {

OpenMagnetics::Core quick_core(const std::string& shapeName) {
    return OpenMagneticsTesting::get_quick_core(shapeName, json::parse("[]"), 1, "N87");
}

// Pins lie wholly outside the core's bounding volume (|x| <= width/2, |y| <= height/2,
// |z| <= depth/2, centred on the main column): the ABT #1207 check, for both orientations.
void check_pins_outside_core(const std::vector<MAS::Pin>& pins, const OpenMagnetics::Core& core, OrientationEnum orientation) {
    const double halfHeight = core.get_height() / 2;
    const double halfDepth = core.get_depth() / 2;
    for (const auto& pin : pins) {
        const auto coordinates = pin.get_coordinates().value();
        const auto dimensions = pin.get_dimensions();
        INFO("pin " << pin.get_name().value() << " at {" << coordinates[0] << ", " << coordinates[1] << ", " << coordinates[2] << "}");
        if (orientation == OrientationEnum::VERTICAL) {
            // Length along Y: the top end is the rail face, below the core's bottom face.
            CHECK(coordinates[1] + dimensions[2] / 2 < -halfHeight);
            CHECK(std::abs(coordinates[2]) - dimensions[0] / 2 > halfDepth);
            CHECK_FALSE(pin.get_rotation());
        }
        else {
            // Length along Z: the near end is the rail face, beyond the core's depth face.
            CHECK(coordinates[2] + dimensions[2] / 2 < -halfDepth);
            REQUIRE(pin.get_rotation());
        }
    }
}

}  // namespace

TEST_CASE("Quick bobbin pins are off by default: the bobbin is the same, with no pins (ABT #1220)",
          "[constructive-model][bobbin][pins][abt1220]") {
    settings.reset();
    for (const std::string shapeName : {"E 42/21/15", "PQ 32/30", "ETD 34/17/11"}) {
        INFO(shapeName);
        auto core = quick_core(shapeName);
        json byDefault;
        json explicitlyOff;
        to_json(byDefault, static_cast<MAS::Bobbin>(OpenMagnetics::Bobbin::create_quick_bobbin(core)));
        to_json(explicitlyOff, static_cast<MAS::Bobbin>(OpenMagnetics::Bobbin::create_quick_bobbin(core, false, std::nullopt)));
        CHECK(byDefault == explicitlyOff);
        REQUIRE(byDefault.contains("processedDescription"));
        // The generated to_json writes absent optionals as null.
        CHECK(byDefault["processedDescription"]["pins"].is_null());
        CHECK(byDefault["functionalDescription"].is_null());

        json thickness;
        to_json(thickness, static_cast<MAS::Bobbin>(OpenMagnetics::Bobbin::create_quick_bobbin(core, 0.001, 0.001)));
        CHECK(thickness["processedDescription"]["pins"].is_null());

        // Asking for pins changes ONLY the pins: every other processed field is untouched.
        json withPins;
        to_json(withPins, static_cast<MAS::Bobbin>(OpenMagnetics::Bobbin::create_quick_bobbin(core, false, OrientationEnum::VERTICAL)));
        REQUIRE(withPins["processedDescription"]["pins"].is_array());
        withPins["processedDescription"]["pins"] = nullptr;
        CHECK(withPins == byDefault);
    }
}

TEST_CASE("Vertical quick bobbin pins follow the catalogue table (ABT #1220)",
          "[constructive-model][bobbin][pins][abt1220]") {
    SECTION("E 42/21/15: 8 + 8 at 5.08 mm, rows 25.4 mm apart") {
        auto core = quick_core("E 42/21/15");
        CHECK_THAT(core.get_width(), Catch::Matchers::WithinAbs(0.04215, 1e-9));
        CHECK_THAT(core.get_height(), Catch::Matchers::WithinAbs(0.042, 1e-9));
        CHECK_THAT(core.get_depth(), Catch::Matchers::WithinAbs(0.01495, 1e-9));
        auto synthesised = OpenMagnetics::Bobbin::synthesise_quick_bobbin_pinout(core, OrientationEnum::VERTICAL);
        CHECK(synthesised.rulesClass == "E-type");
        // 42.15 mm >= 17.85 mm -> 5.08 mm; floor((42.15 - 2 x 2.00) / 5.08) + 1 = floor(7.51) + 1 = 8.
        CHECK(synthesised.pinout.get_number_pins() == 16);
        CHECK(synthesised.pinout.get_number_pins_per_row().value() == std::vector<int64_t>({8, 8}));
        CHECK_THAT(std::get<double>(synthesised.pinout.get_pitch().value()), Catch::Matchers::WithinAbs(0.00508, 1e-12));
        // ceil((14.95 + 2 x 4.70) / 2.54) x 2.54 = ceil(9.59) x 2.54 = 25.4 mm.
        CHECK_THAT(synthesised.pinout.get_row_distance().value(), Catch::Matchers::WithinAbs(0.0254, 1e-12));
        // Rail: 42.0 / 2 + 2.372 = 23.372 mm below the column centre (ABT #1249; was 27.52 with
        // ABT #1207's 6.52 mm standoff, which included the Miles-Platts tab height).
        CHECK_THAT(synthesised.pinRailDistance, Catch::Matchers::WithinAbs(0.023372, 1e-9));
        const auto description = synthesised.pinout.get_pin_description().value();
        CHECK(description.get_shape() == PinShape::ROUND);
        CHECK(description.get_type() == PinDescriptionType::THT);
        CHECK(description.get_dimensions() == std::vector<double>({0.00091, 0.00091, 0.00635}));

        auto bobbin = OpenMagnetics::Bobbin::create_quick_bobbin(core, false, OrientationEnum::VERTICAL);
        auto pins = bobbin.get_processed_description()->get_pins().value();
        REQUIRE(pins.size() == 16);
        // Counter-clockwise from the far end of row 0: 1..8 along +X at z = -12.7 mm, 9..16 back
        // along -X at z = +12.7 mm; x = (i - 3.5) x 5.08 mm.
        for (size_t index = 0; index < 16; ++index) {
            const auto coordinates = pins[index].get_coordinates().value();
            CHECK(pins[index].get_name().value() == std::to_string(index + 1));
            const double along = index < 8 ? (index - 3.5) * 0.00508 : (11.5 - index) * 0.00508;
            CHECK_THAT(coordinates[0], Catch::Matchers::WithinAbs(along, 1e-9));
            CHECK_THAT(coordinates[2], Catch::Matchers::WithinAbs(index < 8 ? -0.0127 : 0.0127, 1e-12));
            // -(23.372 + 6.35 / 2) = -26.547 mm.
            CHECK_THAT(coordinates[1], Catch::Matchers::WithinAbs(-0.026547, 1e-9));
        }
        check_pins_outside_core(pins, core, OrientationEnum::VERTICAL);
        CHECK(bobbin.get_pin("16").get_coordinates().value()[0] < 0);
    }

    SECTION("PQ 32/30: 6 + 6 at 5.08 mm, rows 30.48 mm apart - the Miles-Platts PQ 32/30 footprint's own counts") {
        auto core = quick_core("PQ 32/30");
        auto synthesised = OpenMagnetics::Bobbin::synthesise_quick_bobbin_pinout(core, OrientationEnum::VERTICAL);
        CHECK(synthesised.rulesClass == "PQ");
        // 32 mm >= 29.25 mm -> 5.08 mm; floor((32 - 2 x 2.03) / 5.08) + 1 = floor(5.50) + 1 = 6.
        CHECK(synthesised.pinout.get_number_pins_per_row().value() == std::vector<int64_t>({6, 6}));
        CHECK_THAT(std::get<double>(synthesised.pinout.get_pitch().value()), Catch::Matchers::WithinAbs(0.00508, 1e-12));
        // ceil((22 + 2 x 3.72) / 2.54) x 2.54 = ceil(11.59) x 2.54 = 30.48 mm.
        CHECK_THAT(synthesised.pinout.get_row_distance().value(), Catch::Matchers::WithinAbs(0.03048, 1e-12));
        CHECK_THAT(synthesised.pinRailDistance, Catch::Matchers::WithinAbs(core.get_height() / 2 + 0.002372, 1e-12));
        auto bobbin = OpenMagnetics::Bobbin::create_quick_bobbin(core, false, OrientationEnum::VERTICAL);
        check_pins_outside_core(bobbin.get_processed_description()->get_pins().value(), core, OrientationEnum::VERTICAL);
    }

    SECTION("ETD 34/17/11: 6 + 6 at 5.08 mm, rows 20.32 mm apart") {
        auto core = quick_core("ETD 34/17/11");
        auto synthesised = OpenMagnetics::Bobbin::synthesise_quick_bobbin_pinout(core, OrientationEnum::VERTICAL);
        // floor((34.2 - 4.00) / 5.08) + 1 = floor(5.94) + 1 = 6; ceil((10.8 + 9.4) / 2.54) = ceil(7.95) = 8 -> 20.32 mm.
        CHECK(synthesised.pinout.get_number_pins_per_row().value() == std::vector<int64_t>({6, 6}));
        CHECK_THAT(synthesised.pinout.get_row_distance().value(), Catch::Matchers::WithinAbs(0.02032, 1e-12));
        auto bobbin = OpenMagnetics::Bobbin::create_quick_bobbin(core, 0.001, 0.001, OrientationEnum::VERTICAL);
        check_pins_outside_core(bobbin.get_processed_description()->get_pins().value(), core, OrientationEnum::VERTICAL);
    }
}

TEST_CASE("Horizontal quick bobbin pins sit one row per end flange and clear the core depth (ABT #1220)",
          "[constructive-model][bobbin][pins][abt1220]") {
    auto core = quick_core("ETD 34/17/11");
    const double windowHeight = core.get_processed_description()->get_winding_windows()[0].get_height().value();
    CHECK_THAT(windowHeight, Catch::Matchers::WithinAbs(0.0242, 1e-9));
    auto synthesised = OpenMagnetics::Bobbin::synthesise_quick_bobbin_pinout(core, OrientationEnum::HORIZONTAL);
    CHECK(synthesised.pinout.get_number_pins_per_row().value() == std::vector<int64_t>({6, 6}));
    // ceil((24.2 + 2 x 1.55) / 2.54) x 2.54 = ceil(10.75) x 2.54 = 27.94 mm.
    CHECK_THAT(synthesised.pinout.get_row_distance().value(), Catch::Matchers::WithinAbs(0.02794, 1e-12));
    // Rail: depth 10.8 / 2 + 2.372 = 7.772 mm along -Z (ABT #1249; was 11.92 mm).
    CHECK_THAT(synthesised.pinRailDistance, Catch::Matchers::WithinAbs(0.007772, 1e-9));

    auto bobbin = OpenMagnetics::Bobbin::create_quick_bobbin(core, false, OrientationEnum::HORIZONTAL);
    auto pins = bobbin.get_processed_description()->get_pins().value();
    REQUIRE(pins.size() == 12);
    for (size_t index = 0; index < pins.size(); ++index) {
        const auto coordinates = pins[index].get_coordinates().value();
        CHECK_THAT(coordinates[1], Catch::Matchers::WithinAbs(index < 6 ? -0.01397 : 0.01397, 1e-12));
        // Beyond the end flanges: past half the window height.
        CHECK(std::abs(coordinates[1]) > windowHeight / 2);
        CHECK_THAT(coordinates[2], Catch::Matchers::WithinAbs(-(0.007772 + 0.00635 / 2), 1e-9));
    }
    check_pins_outside_core(pins, core, OrientationEnum::HORIZONTAL);

    // No horizontal PQ former in the catalogue: no row distance to size, so no pins.
    CHECK_THROWS_WITH(OpenMagnetics::Bobbin::synthesise_quick_bobbin_pinout(quick_core("PQ 32/30"), OrientationEnum::HORIZONTAL),
                      Catch::Matchers::ContainsSubstring("no horizontal former of class PQ"));
}

TEST_CASE("A small core carries 2+ pins a row or throws with the numbers; an unevidenced family throws (ABT #1220)",
          "[constructive-model][bobbin][pins][abt1220]") {
    SECTION("E 13/7/4 fits 4 + 4 at 2.54 mm") {
        auto core = quick_core("E 13/7/4");
        auto synthesised = OpenMagnetics::Bobbin::synthesise_quick_bobbin_pinout(core, OrientationEnum::VERTICAL);
        // 12.65 mm < 13.825 mm -> 2.54 mm (MAS a392f1e: Norwe formers on 10 and 12.65 mm cores);
        // floor((12.65 - 2 x 1.981) / 2.54) + 1 = floor(3.42) + 1 = 4; ceil((3.55 + 9.4) / 2.54) = ceil(5.10) = 6 -> 15.24 mm.
        CHECK(synthesised.pinout.get_number_pins_per_row().value() == std::vector<int64_t>({4, 4}));
        CHECK_THAT(std::get<double>(synthesised.pinout.get_pitch().value()), Catch::Matchers::WithinAbs(0.00254, 1e-12));
        CHECK_THAT(synthesised.pinout.get_row_distance().value(), Catch::Matchers::WithinAbs(0.01524, 1e-12));
        auto bobbin = OpenMagnetics::Bobbin::create_quick_bobbin(core, false, OrientationEnum::VERTICAL);
        check_pins_outside_core(bobbin.get_processed_description()->get_pins().value(), core, OrientationEnum::VERTICAL);
    }
    SECTION("E 5.3/2 holds one pin a row and throws") {
        auto core = quick_core("E 5.3/2");
        // 5.25 - 2 x 1.981 = 1.288 mm: one pin at 2.54 mm. The 1.981 mm edge margin is the derived
        // E-type median since MAS a349132 corrected 14 Norwe pin fields (was 2.00 mm, leaving 1.25 mm);
        // the verdict is unchanged.
        CHECK_THROWS_WITH(OpenMagnetics::Bobbin::create_quick_bobbin(core, false, OrientationEnum::VERTICAL),
                          Catch::Matchers::ContainsSubstring("width of 5.250 mm") &&
                          Catch::Matchers::ContainsSubstring("leaves 1.288 mm") &&
                          Catch::Matchers::ContainsSubstring("holds 1 pin(s) at the 2.540 mm pitch") &&
                          Catch::Matchers::ContainsSubstring("at least 2"));
        // Off, the same core still gets its quick bobbin.
        CHECK_NOTHROW(OpenMagnetics::Bobbin::create_quick_bobbin(core, false));
    }
    SECTION("a toroid and a U core have no catalogue former with pin geometry") {
        CHECK_THROWS_WITH(OpenMagnetics::Bobbin::create_quick_bobbin(quick_core("T 20/10/7"), false, OrientationEnum::VERTICAL),
                          Catch::Matchers::ContainsSubstring("core family 't'"));
        CHECK_THROWS_WITH(OpenMagnetics::Bobbin::synthesise_quick_bobbin_pinout(quick_core("U 20/16/7"), OrientationEnum::VERTICAL),
                          Catch::Matchers::ContainsSubstring("core family 'u'"));
    }
}

TEST_CASE("assign_pins works on a quick bobbin with synthesised pins: flyback sides on opposite rows (ABT #1220)",
          "[constructive-model][coil][pins][abt1220]") {
    settings.reset();
    auto core = quick_core("PQ 32/30");
    auto bobbin = OpenMagnetics::Bobbin::create_quick_bobbin(core, false, OrientationEnum::VERTICAL);

    json coilJson;
    to_json(coilJson["bobbin"], static_cast<MAS::Bobbin>(bobbin));
    coilJson["functionalDescription"] = json::array();
    for (const auto& [name, turns, side] : std::vector<std::tuple<std::string, int64_t, std::string>>{
             {"Primary", 40, "primary"}, {"Secondary", 6, "secondary"}}) {
        json winding;
        winding["name"] = name;
        winding["numberTurns"] = turns;
        winding["numberParallels"] = 1;
        winding["isolationSide"] = side;
        winding["wire"] = "Round 0.5 - Grade 1";
        coilJson["functionalDescription"].push_back(winding);
    }
    OpenMagnetics::Coil coil(coilJson, false);
    REQUIRE(coil.wind());
    auto result = coil.assign_pins(coil.resolve_bobbin(), core);
    CHECK_FALSE(result.skipped);
    REQUIRE(coil.has_complete_pin_connections());

    auto placed = OpenMagnetics::Coil::place_pins(coil.resolve_bobbin().get_processed_description()->get_pins().value());
    auto row_of = [&](const std::string& winding) {
        std::set<size_t> rows;
        for (const auto& w : coil.get_functional_description()) {
            if (w.get_name() != winding) {
                continue;
            }
            const auto connections = w.get_connections().value();
            for (const auto& connection : connections) {
                for (const auto& pin : placed) {
                    if (pin.name == connection.get_pin_name().value()) {
                        rows.insert(pin.row);
                    }
                }
            }
        }
        return rows;
    };
    auto primaryRows = row_of("Primary");
    auto secondaryRows = row_of("Secondary");
    REQUIRE(primaryRows.size() == 1);
    REQUIRE(secondaryRows.size() == 1);
    CHECK(*primaryRows.begin() != *secondaryRows.begin());
}

TEST_CASE("magnetic_autocomplete gives a Basic quick bobbin pins only when the setting asks (ABT #1220)",
          "[constructive-model][bobbin][pins][abt1220][masautocomplete]") {
    settings.reset();
    auto build = []() {
        json coilJson;
        coilJson["bobbin"] = "Basic";
        coilJson["functionalDescription"] = json::array();
        for (const auto& [name, turns, side] : std::vector<std::tuple<std::string, int64_t, std::string>>{
                 {"Primary", 30, "primary"}, {"Secondary", 5, "secondary"}}) {
            json winding;
            winding["name"] = name;
            winding["numberTurns"] = turns;
            winding["numberParallels"] = 1;
            winding["isolationSide"] = side;
            winding["wire"] = "Round 0.5 - Grade 1";
            coilJson["functionalDescription"].push_back(winding);
        }
        OpenMagnetics::Magnetic magnetic;
        magnetic.set_core(quick_core("E 42/21/15"));
        magnetic.set_coil(OpenMagnetics::Coil(coilJson, false));
        return OpenMagnetics::magnetic_autocomplete(magnetic);
    };

    SECTION("off (default): no pins, no pin names") {
        CHECK_FALSE(settings.get_coil_quick_bobbin_generate_pins());
        auto magnetic = build();
        auto bobbin = magnetic.get_mutable_coil().resolve_bobbin();
        CHECK_FALSE(bobbin.get_processed_description()->get_pins());
        for (const auto& winding : magnetic.get_coil().get_functional_description()) {
            if (winding.get_connections()) {
                const auto connections = winding.get_connections().value();
                for (const auto& connection : connections) {
                    CHECK_FALSE(connection.get_pin_name());
                }
            }
        }
    }
    SECTION("on: 16 vertical pins, every winding end on a pin") {
        settings.set_coil_quick_bobbin_generate_pins(true);
        // ABT #1237: autocomplete connects the leads to the pins only when asked.
        settings.set_coil_connect_leads_to_pins(true);
        auto magnetic = build();
        auto bobbin = magnetic.get_mutable_coil().resolve_bobbin();
        REQUIRE(bobbin.get_processed_description()->get_pins());
        CHECK(bobbin.get_processed_description()->get_pins()->size() == 16);
        CHECK(magnetic.get_mutable_coil().has_complete_pin_connections());
        settings.reset();
    }
}

TEST_CASE("scripts/derive_quick_bobbin_pins.py reproduces the committed table (ABT #1220)",
          "[bobbin][pins][abt1220]") {
    const auto root = std::filesystem::path{std::source_location::current().file_name()}.parent_path().parent_path();
    const std::string command = "python3 \"" + (root / "scripts" / "derive_quick_bobbin_pins.py").string() + "\" --check";
    CHECK(std::system(command.c_str()) == 0);
}
