#include "processors/CircuitSimulatorInterface.h"
#include "support/Exceptions.h"
#include "TestingUtils.h"
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <source_location>

using namespace OpenMagnetics;
using Catch::Matchers::ContainsSubstring;

// Tests for the CircuitSimulationReader parser robustness improvements.
// These cover bugs and gaps identified in the importer review:
//   - empty-token undefined behaviour
//   - UTF-8 BOM in the first header byte
//   - comment / blank lines before the header
//   - error context (line + column) when std::stod fails
//   - guess_separator picking the highest-column-count candidate
//   - quoted-field stripping in both header and data rows
//   - CRLF handling in the data branch

TEST_CASE("Reader: parses a minimal CSV cleanly", "[processor][circuit-simulation-reader][robustness]") {
    std::string csv =
        "time,Iout\n"
        "0.0,0.0\n"
        "1e-6,1.0\n"
        "2e-6,2.0\n";
    REQUIRE_NOTHROW(CircuitSimulationReader(csv, true));
}

TEST_CASE("Reader: strips UTF-8 BOM from the first header byte", "[processor][circuit-simulation-reader][robustness]") {
    // Excel-saved CSVs prepend EF BB BF. Without stripping, the first column
    // name becomes "﻿time" and breaks name-based time detection.
    std::string csv = "\xEF\xBB\xBF" "time,Iout\n0,0\n1e-6,1\n2e-6,2\n";
    CircuitSimulationReader reader(csv, true);
    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 2);
    REQUIRE(names[0] == "time");  // BOM gone
    REQUIRE(names[1] == "Iout");
}

TEST_CASE("Reader: skips '#' / '!' / '*' / '//' comment lines before the header",
          "[processor][circuit-simulation-reader][robustness]") {
    std::string csv =
        "# generated by my-sim 3.2\n"
        "* SPICE-style comment\n"
        "! another comment\n"
        "// C-style comment\n"
        "\n"
        "time,Iout\n"
        "0,0\n"
        "1e-6,1\n";
    CircuitSimulationReader reader(csv, true);
    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 2);
    REQUIRE(names[0] == "time");
    REQUIRE(names[1] == "Iout");
}

TEST_CASE("Reader: rejects an empty input with a clear message",
          "[processor][circuit-simulation-reader][robustness]") {
    REQUIRE_THROWS_AS(CircuitSimulationReader("", true), InvalidInputException);
}

TEST_CASE("Reader: rejects a comment-only input with a clear message",
          "[processor][circuit-simulation-reader][robustness]") {
    std::string csv = "# nothing here\n# really nothing\n";
    REQUIRE_THROWS_AS(CircuitSimulationReader(csv, true), InvalidInputException);
}

TEST_CASE("Reader: stod failure carries line + column + token context",
          "[processor][circuit-simulation-reader][robustness]") {
    std::string csv =
        "time,Iout\n"
        "0,0\n"
        "1e-6,not_a_number\n";
    try {
        CircuitSimulationReader reader(csv, true);
        FAIL("expected an exception");
    }
    catch (const std::exception& e) {
        std::string msg = e.what();
        REQUIRE_THAT(msg, ContainsSubstring("line"));
        REQUIRE_THAT(msg, ContainsSubstring("Iout"));        // column name in message
        REQUIRE_THAT(msg, ContainsSubstring("not_a_number")); // offending token
    }
}

TEST_CASE("Reader: trailing CR (CRLF endings) does not break the data branch",
          "[processor][circuit-simulation-reader][robustness]") {
    // CRLF on data rows used to slip into the *last* token as "1.0\r" and
    // throw inside std::stod, which was then swallowed by catch(...).
    std::string csv =
        "time,Iout\r\n"
        "0,0\r\n"
        "1e-6,1.0\r\n"
        "2e-6,2.0\r\n";
    REQUIRE_NOTHROW(CircuitSimulationReader(csv, true));
}

TEST_CASE("Reader: empty trailing field (PSIM-style trailing comma) is tolerated",
          "[processor][circuit-simulation-reader][robustness]") {
    // Two adjacent separators used to read an empty token and dereference
    // token[0] — UB. After the fix, empty tokens are skipped.
    std::string csv =
        "time,Iout,\n"
        "0,0,\n"
        "1e-6,1.0,\n";
    REQUIRE_NOTHROW(CircuitSimulationReader(csv, true));
}

TEST_CASE("guess_separator: picks the candidate with the most columns (highest-count wins)",
          "[processor][circuit-simulation-reader][robustness]") {
    // A semicolon-separated header with quoted commas inside fields used to
    // be mis-detected as comma-separated.
    std::string headerSemicolon = "\"Voltage, primary\";\"Current, primary\";\"Time / s\"";
    REQUIRE(';' == CircuitSimulationReader::guess_separator(headerSemicolon));
}

TEST_CASE("guess_separator: pipe-delimited is now supported",
          "[processor][circuit-simulation-reader][robustness]") {
    std::string row = "time|Ipri|Vpri";
    REQUIRE('|' == CircuitSimulationReader::guess_separator(row));
}

TEST_CASE("guess_separator: a single-column header throws a clear error",
          "[processor][circuit-simulation-reader][robustness]") {
    REQUIRE_THROWS_AS(CircuitSimulationReader::guess_separator("just_one_column"),
                      InvalidInputException);
}

TEST_CASE("Reader: header with quoted commas keeps the comma inside the name (semicolon-separated)",
          "[processor][circuit-simulation-reader][robustness]") {
    std::string csv =
        "\"Time / s\";\"Voltage, primary\";\"Current, primary\"\n"
        "0;0;0\n"
        "1e-6;48.0;0.1\n";
    CircuitSimulationReader reader(csv, true);
    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 3);
    REQUIRE(names[0] == "Time / s");
    REQUIRE(names[1] == "Voltage, primary");  // comma preserved inside quotes
    REQUIRE(names[2] == "Current, primary");
}

TEST_CASE("guess_separator: ignores commas inside an LTspice differential probe V(a,b)",
          "[processor][circuit-simulation-reader][robustness]") {
    // LTspice writes the differential-voltage probe unquoted as V(node_p,node_n).
    // The comma inside the parentheses must not be counted as a separator, or a
    // comma-separated file is mis-split (one extra column in the header).
    std::string header = "time,V(N009,d),V(n016),V(n017),I(L1),I(L3),I(L4)";
    REQUIRE(',' == CircuitSimulationReader::guess_separator(header));
}

TEST_CASE("Reader: LTspice differential probe V(a,b) stays a single column (comma-separated)",
          "[processor][circuit-simulation-reader][robustness]") {
    // Regression for the broken CSV upload: the unquoted comma inside V(N009,d)
    // used to split the header into 8 fields while data rows had 7, shifting
    // every column left by one. The header must now yield exactly 7 columns
    // with the differential probe preserved verbatim.
    std::string csv =
        "time,V(N009,d),V(n016),V(n017),I(L1),I(L3),I(L4)\n"
        "0.0,-19.1,13.9,6.97,-2.9e-4,1.24,3.9e-4\n"
        "1e-9,-19.1,13.9,6.97,-3.2e-4,1.24,3.8e-4\n";
    CircuitSimulationReader reader(csv, true);
    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 7);
    REQUIRE(names[0] == "time");
    REQUIRE(names[1] == "V(N009,d)");  // comma preserved inside the parentheses
    REQUIRE(names[2] == "V(n016)");
    REQUIRE(names[6] == "I(L4)");
}

TEST_CASE("Reader: parses the real LTspice flyback export with a differential probe",
          "[processor][circuit-simulation-reader][robustness]") {
    // Trimmed copy of a user's LTspice 'Export data as text' CSV (fly_2out.txt)
    // whose header is: time,V(N009,d),V(n016),V(n017),I(L1),I(L3),I(L4)
    // It uses CRLF endings and the unquoted differential probe V(N009,d).
    auto path = OpenMagneticsTesting::get_test_data_path(std::source_location::current(), "ltspice_flyback_diff_probe.csv");
    CircuitSimulationReader reader(path.string());  // file mode (not forceFile)

    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 7);
    REQUIRE(names[1] == "V(N009,d)");

    // Every column must be fully populated and aligned: a misaligned split would
    // leave the trailing column empty or with a different length.
    const auto& columns = reader.get_columns();
    REQUIRE(columns.size() == 7);
    size_t expectedSamples = columns[0].data.size();
    REQUIRE(expectedSamples > 0);
    for (const auto& column : columns) {
        REQUIRE(column.data.size() == expectedSamples);
    }
}
