#include "processors/CircuitSimulatorInterface.h"
#include "support/Exceptions.h"
#include "TestingUtils.h"
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <source_location>
#include <sstream>

using namespace OpenMagnetics;
using Catch::Matchers::ContainsSubstring;

// Tests for the CircuitSimulationReader parser robustness improvements.
// These cover bugs and gaps identified in the importer review:
//   - empty-token undefined behaviour
//   - UTF-8 BOM in the first header byte
//   - comment / blank lines before the header
//   - error context (line + column) when std::stod fails
//   - guess_separator picking the highest-column-count candidate
//   - quoted-field stripping in both header and data rows
//   - CRLF handling in the data branch

TEST_CASE("Reader: parses a minimal CSV cleanly", "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    std::string csv =
        "time,Iout\n"
        "0.0,0.0\n"
        "1e-6,1.0\n"
        "2e-6,2.0\n";
    REQUIRE_NOTHROW(CircuitSimulationReader(csv, true));
}

TEST_CASE("Reader: strips UTF-8 BOM from the first header byte", "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // Excel-saved CSVs prepend EF BB BF. Without stripping, the first column
    // name becomes "﻿time" and breaks name-based time detection.
    std::string csv = "\xEF\xBB\xBF" "time,Iout\n0,0\n1e-6,1\n2e-6,2\n";
    CircuitSimulationReader reader(csv, true);
    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 2);
    REQUIRE(names[0] == "time");  // BOM gone
    REQUIRE(names[1] == "Iout");
}

TEST_CASE("Reader: skips '#' / '!' / '*' / '//' comment lines before the header",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    std::string csv =
        "# generated by my-sim 3.2\n"
        "* SPICE-style comment\n"
        "! another comment\n"
        "// C-style comment\n"
        "\n"
        "time,Iout\n"
        "0,0\n"
        "1e-6,1\n";
    CircuitSimulationReader reader(csv, true);
    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 2);
    REQUIRE(names[0] == "time");
    REQUIRE(names[1] == "Iout");
}

TEST_CASE("Reader: rejects an empty input with a clear message",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    REQUIRE_THROWS_AS(CircuitSimulationReader("", true), InvalidInputException);
}

TEST_CASE("Reader: rejects a comment-only input with a clear message",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    std::string csv = "# nothing here\n# really nothing\n";
    REQUIRE_THROWS_AS(CircuitSimulationReader(csv, true), InvalidInputException);
}

TEST_CASE("Reader: stod failure carries line + column + token context",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    std::string csv =
        "time,Iout\n"
        "0,0\n"
        "1e-6,not_a_number\n";
    try {
        CircuitSimulationReader reader(csv, true);
        FAIL("expected an exception");
    }
    catch (const std::exception& e) {
        std::string msg = e.what();
        REQUIRE_THAT(msg, ContainsSubstring("line"));
        REQUIRE_THAT(msg, ContainsSubstring("Iout"));        // column name in message
        REQUIRE_THAT(msg, ContainsSubstring("not_a_number")); // offending token
    }
}

TEST_CASE("Reader: trailing CR (CRLF endings) does not break the data branch",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // CRLF on data rows used to slip into the *last* token as "1.0\r" and
    // throw inside std::stod, which was then swallowed by catch(...).
    std::string csv =
        "time,Iout\r\n"
        "0,0\r\n"
        "1e-6,1.0\r\n"
        "2e-6,2.0\r\n";
    REQUIRE_NOTHROW(CircuitSimulationReader(csv, true));
}

TEST_CASE("Reader: empty trailing field (PSIM-style trailing comma) is tolerated",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // Two adjacent separators used to read an empty token and dereference
    // token[0] — UB. After the fix, empty tokens are skipped.
    std::string csv =
        "time,Iout,\n"
        "0,0,\n"
        "1e-6,1.0,\n";
    REQUIRE_NOTHROW(CircuitSimulationReader(csv, true));
}

TEST_CASE("guess_separator: picks the candidate with the most columns (highest-count wins)",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // A semicolon-separated header with quoted commas inside fields used to
    // be mis-detected as comma-separated.
    std::string headerSemicolon = "\"Voltage, primary\";\"Current, primary\";\"Time / s\"";
    REQUIRE(';' == CircuitSimulationReader::guess_separator(headerSemicolon));
}

TEST_CASE("guess_separator: pipe-delimited is now supported",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    std::string row = "time|Ipri|Vpri";
    REQUIRE('|' == CircuitSimulationReader::guess_separator(row));
}

TEST_CASE("guess_separator: a single-column header throws a clear error",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    REQUIRE_THROWS_AS(CircuitSimulationReader::guess_separator("just_one_column"),
                      InvalidInputException);
}

TEST_CASE("Reader: header with quoted commas keeps the comma inside the name (semicolon-separated)",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    std::string csv =
        "\"Time / s\";\"Voltage, primary\";\"Current, primary\"\n"
        "0;0;0\n"
        "1e-6;48.0;0.1\n";
    CircuitSimulationReader reader(csv, true);
    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 3);
    REQUIRE(names[0] == "Time / s");
    REQUIRE(names[1] == "Voltage, primary");  // comma preserved inside quotes
    REQUIRE(names[2] == "Current, primary");
}

TEST_CASE("guess_separator: ignores commas inside an LTspice differential probe V(a,b)",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // LTspice writes the differential-voltage probe unquoted as V(node_p,node_n).
    // The comma inside the parentheses must not be counted as a separator, or a
    // comma-separated file is mis-split (one extra column in the header).
    std::string header = "time,V(N009,d),V(n016),V(n017),I(L1),I(L3),I(L4)";
    REQUIRE(',' == CircuitSimulationReader::guess_separator(header));
}

TEST_CASE("Reader: LTspice differential probe V(a,b) stays a single column (comma-separated)",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // Regression for the broken CSV upload: the unquoted comma inside V(N009,d)
    // used to split the header into 8 fields while data rows had 7, shifting
    // every column left by one. The header must now yield exactly 7 columns
    // with the differential probe preserved verbatim.
    std::string csv =
        "time,V(N009,d),V(n016),V(n017),I(L1),I(L3),I(L4)\n"
        "0.0,-19.1,13.9,6.97,-2.9e-4,1.24,3.9e-4\n"
        "1e-9,-19.1,13.9,6.97,-3.2e-4,1.24,3.8e-4\n";
    CircuitSimulationReader reader(csv, true);
    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 7);
    REQUIRE(names[0] == "time");
    REQUIRE(names[1] == "V(N009,d)");  // comma preserved inside the parentheses
    REQUIRE(names[2] == "V(n016)");
    REQUIRE(names[6] == "I(L4)");
}

// Build a CSV carrying two independent acquisitions side by side, the way lab
// exports merge several measurements into one file: each sweep has its own
// time column with its own sample instants. Sweep 1 samples every 5e-7 s
// (a 10 kHz triangle 100..200 A), sweep 2 every 4e-7 s (100..300 A).
// `sweep2Rows` allows truncating the second acquisition early (empty cells),
// which is how ragged multi-acquisition exports look.
static std::string build_two_acquisition_csv(size_t rows, size_t sweep2Rows) {
    auto triangle = [](double t, double lo, double hi) {
        double phase = t * 10e3 - std::floor(t * 10e3);
        return lo + (hi - lo) * (phase < 0.5? 2 * phase : 2 * (1 - phase));
    };
    std::ostringstream csv;
    csv << "Time / s_1,V_1,I_1,Time / s_2,V_2,I_2\n";
    csv.precision(10);
    for (size_t i = 0; i < rows; ++i) {
        double t1 = i * 5e-7;
        csv << t1 << ",10," << triangle(t1, 100, 200) << ",";
        if (i < sweep2Rows) {
            double t2 = i * 4e-7;
            csv << t2 << ",20," << triangle(t2, 100, 300) << "\n";
        }
        else {
            csv << ",,\n";
        }
    }
    return csv.str();
}

TEST_CASE("Reader: signals pair with the time column selected for their winding, not the file's first",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // Regression: every signal used to be paired with the FIRST time-like
    // column, so acquisition 2's current was plotted against acquisition 1's
    // axis. Amplitude statistics survive that warp (both axes are linear), but
    // periodicity does not: the extracted window then spans 0.8 of the true
    // cycle and the waveform ends 80 A away from where it starts.
    auto csv = build_two_acquisition_csv(500, 500);
    CircuitSimulationReader reader(csv, true);
    std::vector<std::map<std::string, std::string>> mapColumnNames = {
        {{"time", "Time / s_2"}, {"current", "I_2"}, {"voltage", "V_2"}}};
    auto operatingPoint = reader.extract_operating_point(1, 10e3, mapColumnNames);
    auto current = operatingPoint.get_excitations_per_winding()[0].get_current().value();
    auto processed = current.get_processed().value();
    CHECK(processed.get_peak().value() > 290);
    CHECK(processed.get_peak_to_peak().value() > 190);
    CHECK(processed.get_peak_to_peak().value() < 210);
    CHECK(std::fabs(processed.get_offset() - 200) < 10);
    auto data = current.get_waveform().value().get_data();
    CHECK(std::fabs(data.front() - data.back()) < 10);
}

TEST_CASE("Reader: ragged multi-acquisition file extracts the shorter sweep correctly",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // Regression for the user-reported import bug: the shorter acquisition's
    // columns (trailing empty cells) used to be sliced with window indexes
    // computed on the longer first time column — an out-of-bounds read that
    // surfaced as a zero tail (peak == peak-to-peak, offset == peak / 2).
    auto csv = build_two_acquisition_csv(500, 400);
    CircuitSimulationReader reader(csv, true);
    std::vector<std::map<std::string, std::string>> mapColumnNames = {
        {{"time", "Time / s_2"}, {"current", "I_2"}, {"voltage", "V_2"}}};
    auto operatingPoint = reader.extract_operating_point(1, 10e3, mapColumnNames);
    auto current = operatingPoint.get_excitations_per_winding()[0].get_current().value();
    auto processed = current.get_processed().value();
    CHECK(processed.get_peak_to_peak().value() > 190);
    CHECK(processed.get_peak_to_peak().value() < 210);
    auto data = current.get_waveform().value().get_data();
    CHECK(*std::min_element(data.begin(), data.end()) > 90);
}

TEST_CASE("Reader: pairing a signal with a time column of a different length throws loudly",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // Picking acquisition 1's time axis for acquisition 2's (shorter) signal
    // cannot be reconciled — reject it with both column names in the message
    // instead of reading past the end of the data.
    auto csv = build_two_acquisition_csv(500, 400);
    CircuitSimulationReader reader(csv, true);
    std::vector<std::map<std::string, std::string>> mapColumnNames = {
        {{"time", "Time / s_1"}, {"current", "I_2"}, {"voltage", "V_1"}}};
    try {
        reader.extract_operating_point(1, 10e3, mapColumnNames);
        FAIL("expected an exception");
    }
    catch (const std::exception& e) {
        std::string msg = e.what();
        REQUIRE_THAT(msg, ContainsSubstring("I_2"));
        REQUIRE_THAT(msg, ContainsSubstring("Time / s_1"));
    }
}

TEST_CASE("Reader: repeated truncated timestamps are collapsed per time axis (keep-last)",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // Exports rounded to few significant figures repeat each timestamp for
    // many consecutive rows. The dedup now runs per (time, signal) pair; the
    // extraction must still succeed and keep sane amplitudes.
    auto triangle = [](double t, double lo, double hi) {
        double phase = t * 10e3 - std::floor(t * 10e3);
        return lo + (hi - lo) * (phase < 0.5? 2 * phase : 2 * (1 - phase));
    };
    std::ostringstream csv;
    csv << "Time / s,V,I\n";
    for (size_t i = 0; i < 500; ++i) {
        double t = 0.28996 + i * 5e-7;
        char timeToken[32];
        std::snprintf(timeToken, sizeof(timeToken), "%.5f", t);
        csv << timeToken << ",10," << triangle(t, 100, 200) << "\n";
    }
    CircuitSimulationReader reader(csv.str(), true);
    std::vector<std::map<std::string, std::string>> mapColumnNames = {
        {{"time", "Time / s"}, {"current", "I"}, {"voltage", "V"}}};
    auto operatingPoint = reader.extract_operating_point(1, 10e3, mapColumnNames);
    auto current = operatingPoint.get_excitations_per_winding()[0].get_current().value();
    auto processed = current.get_processed().value();
    CHECK(processed.get_peak().value() <= 200.5);
    CHECK(processed.get_peak().value() > 150);
    CHECK(std::fabs(processed.get_offset() - 150) < 25);
}

TEST_CASE("Reader: parses the real LTspice flyback export with a differential probe",
          "[processor][circuit-simulation-reader][robustness][smoke-test]") {
    // Trimmed copy of a user's LTspice 'Export data as text' CSV (fly_2out.txt)
    // whose header is: time,V(N009,d),V(n016),V(n017),I(L1),I(L3),I(L4)
    // It uses CRLF endings and the unquoted differential probe V(N009,d).
    auto path = OpenMagneticsTesting::get_test_data_path(std::source_location::current(), "ltspice_flyback_diff_probe.csv");
    CircuitSimulationReader reader(path.string());  // file mode (not forceFile)

    auto names = reader.extract_column_names();
    REQUIRE(names.size() == 7);
    REQUIRE(names[1] == "V(N009,d)");

    // Every column must be fully populated and aligned: a misaligned split would
    // leave the trailing column empty or with a different length.
    const auto& columns = reader.get_columns();
    REQUIRE(columns.size() == 7);
    size_t expectedSamples = columns[0].data.size();
    REQUIRE(expectedSamples > 0);
    for (const auto& column : columns) {
        REQUIRE(column.data.size() == expectedSamples);
    }
}
