/**
 * End-to-end MagneticAdviser coverage for converter-model variants that lacked
 * any STRONG (REQUIRE(size >= 1)) adviser test. Each section drives
 * MagneticAdviser::get_advised_magnetic_from_converter and pins the contract:
 * the wizard MUST return at least one advised magnetic for canonical inputs.
 *
 * Variants exercised here (gaps surfaced by the audit performed in commit
 * 802d47b3, after silent-pass adviser gates were tightened):
 *   - LLC:  HB+FBd, HB+CD, HB+VD, FB+CT, FB+FBd, FB+CD, FB+VD
 *           (LLC HB+CT already covered by Test_MagneticAdviserFromConverter_LLC)
 *   - SRC:  HB+FBd, HB+CT, HB+CD, FB+FBd, FB+CT, FB+CD
 *           (no VOLTAGE_DOUBLER variant exists in SrcRectifierType)
 *
 * If MagneticAdviser fails on any of these inputs, the failure is a real bug
 * to fix in source — never relax the contract to size >= 0.
 */

#include "advisers/MagneticAdviser.h"
#include "converter_models/Llc.h"
#include "converter_models/Src.h"

#include <catch2/catch_test_macros.hpp>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

using namespace OpenMagnetics;
using json = nlohmann::json;

namespace {

// Canonical LLC wizard inputs (mirror Test_MagneticAdviserFromConverter_LLC).
json make_llc_converter_json(const std::string& bridgeType,
                             const std::string& rectifierType) {
    json j;
    j["inputVoltage"] = {{"nominal", 400}, {"minimum", 370}, {"maximum", 410}};
    j["bridgeType"] = bridgeType;
    j["rectifierType"] = rectifierType;
    j["minSwitchingFrequency"] = 80000;
    j["maxSwitchingFrequency"] = 200000;
    j["inductanceRatio"] = 5.0;
    j["qualityFactor"] = 0.4;
    j["efficiency"] = 0.95;
    j["integratedResonantInductor"] = false;
    j["operatingPoints"] = json::array({
        {{"outputVoltages", {12}},
         {"outputCurrents", {10}},
         {"switchingFrequency", 100000},
         {"ambientTemperature", 25}}
    });
    return j;
}

// Canonical SRC wizard inputs (mirror tests/TestSrc.cpp::make_src_json,
// with fr ≈ fsw_nominal so the FHA flow stays above-resonance ZVS).
json make_src_converter_json(const std::string& bridgeType,
                             const std::string& rectifierType) {
    json j;
    j["inputVoltage"]          = {{"nominal", 400}};
    j["minSwitchingFrequency"] = 50000;
    j["maxSwitchingFrequency"] = 200000;
    j["resonantFrequency"]     = 100000;
    j["qualityFactor"]         = 2.0;
    j["bridgeType"]            = bridgeType;
    j["rectifierType"]         = rectifierType;
    j["isolated"]              = true;
    j["operatingPoints"]       = json::array({
        {{"outputVoltages",     {48}},
         {"outputCurrents",     {10}},
         {"switchingFrequency", 100000},
         {"ambientTemperature", 25}}
    });
    return j;
}

} // namespace


// ============================================================================
// LLC variants
// ============================================================================

TEST_CASE("Test_MagneticAdviserFromConverter_LLC_VariantMatrix",
          "[adviser][from-converter][llc-topology][variant-matrix]") {
    struct Variant { std::string bridge; std::string rectifier; std::string label; };
    std::vector<Variant> variants = {
        // HB+CT is the canonical pre-existing case; include it for symmetry
        // so any regression there is caught alongside the new variants.
        {"halfBridge", "centerTapped",   "HB+CT"},
        {"halfBridge", "fullBridge",     "HB+FBd"},
        {"halfBridge", "currentDoubler", "HB+CD"},
        {"fullBridge", "centerTapped",   "FB+CT"},
        {"fullBridge", "fullBridge",     "FB+FBd"},
        {"fullBridge", "currentDoubler", "FB+CD"},
    };

    for (const auto& v : variants) {
        DYNAMIC_SECTION("LLC " << v.label) {
            Llc converter(make_llc_converter_json(v.bridge, v.rectifier));
            converter._assertErrors = true;

            MagneticAdviser adviser;
            auto results = adviser.get_advised_magnetic_from_converter(converter, 1);
            REQUIRE(results.size() >= 1);
            auto& [mas, score] = results[0];
            REQUIRE(score > 0);
        }
    }
}


// FIXME(llc-voltage-doubler): two stacked bugs prevent VD from reaching the
// adviser end-to-end. Tagged [!mayfail] so the contract is visible (we WILL
// fix it) without blocking CI. Do not relax to size >= 0.
//   (1) Llc.cpp::simulate_and_extract_operating_points — SPICE netlist for
//       VOLTAGE_DOUBLER produces "No output file generated by ngspice"
//       (Llc.cpp:1738). Either the VD output-stage subcircuit fails to
//       converge or a node is unresolved. Inspect the generated netlist
//       (set config.keepTempFiles=true) before fixing.
//   (2) The analytical fallback path (process_operating_points) does not
//       populate current.processed() on every VD winding, so the wire-solver
//       throws "[INVALID_WIRE_DATA] Current is not processed" at the first
//       call from CoilAdviser. Mirror what the CT/FB/CD branches do at
//       Llc.cpp:1117–1226 and ensure processed-data is set for every emitted
//       SignalDescriptor.
TEST_CASE("Test_MagneticAdviserFromConverter_LLC_VoltageDoubler",
          "[adviser][from-converter][llc-topology][variant-matrix][!mayfail]") {
    struct Variant { std::string bridge; std::string rectifier; std::string label; };
    std::vector<Variant> variants = {
        {"halfBridge", "voltageDoubler", "HB+VD"},
        {"fullBridge", "voltageDoubler", "FB+VD"},
    };

    for (const auto& v : variants) {
        DYNAMIC_SECTION("LLC " << v.label) {
            Llc converter(make_llc_converter_json(v.bridge, v.rectifier));
            converter._assertErrors = true;

            MagneticAdviser adviser;
            auto results = adviser.get_advised_magnetic_from_converter(converter, 1);
            REQUIRE(results.size() >= 1);
            auto& [mas, score] = results[0];
            REQUIRE(score > 0);
        }
    }
}


// ============================================================================
// SRC variants (SrcRectifierType has no VOLTAGE_DOUBLER member)
// ============================================================================

TEST_CASE("Test_MagneticAdviserFromConverter_SRC_VariantMatrix",
          "[adviser][from-converter][src-topology][variant-matrix]") {
    struct Variant { std::string bridge; std::string rectifier; std::string label; };
    std::vector<Variant> variants = {
        {"halfBridge", "fullBridgeDiode",   "HB+FBd"},
        {"halfBridge", "centerTappedDiode", "HB+CT"},
        {"halfBridge", "currentDoubler",    "HB+CD"},
        {"fullBridge", "fullBridgeDiode",   "FB+FBd"},
        {"fullBridge", "centerTappedDiode", "FB+CT"},
        {"fullBridge", "currentDoubler",    "FB+CD"},
    };

    for (const auto& v : variants) {
        DYNAMIC_SECTION("SRC " << v.label) {
            Src converter(make_src_converter_json(v.bridge, v.rectifier));

            MagneticAdviser adviser;
            auto results = adviser.get_advised_magnetic_from_converter(converter, 1);
            REQUIRE(results.size() >= 1);
            auto& [mas, score] = results[0];
            REQUIRE(score > 0);
        }
    }
}
