#!/usr/bin/env python3
"""
Generate src/support/CciCoordinatesData.cpp from cci_coords text files.
Only embeds N <= MAX_STRANDS; larger N falls back to the spiral algorithm.
"""
import os
import sys

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <cci_coords_dir> <output_cpp>")
        sys.exit(1)

    cci_dir = sys.argv[1]
    out_path = sys.argv[2]
    max_strands = 1000

    coordinates_dir = os.path.join(cci_dir, "coordinates")
    if not os.path.isdir(coordinates_dir):
        print(f"ERROR: directory not found: {coordinates_dir}")
        sys.exit(1)

    # Collect all files up to max_strands
    entries = []
    for fname in os.listdir(coordinates_dir):
        if not fname.startswith("cci") or not fname.endswith(".txt"):
            continue
        try:
            n = int(fname[3:-4])
        except ValueError:
            continue
        if n <= max_strands:
            entries.append((n, os.path.join(coordinates_dir, fname)))

    entries.sort(key=lambda e: e[0])
    print(f"Embedding {len(entries)} cci coordinate sets (N=1..{max_strands})")

    lines = []
    lines.append("// Auto-generated by scripts/generate_cci_data.py — do not edit")
    lines.append("#include \"CciCoordinatesData.h\"")
    lines.append("#include <unordered_map>")
    lines.append("#include <vector>")
    lines.append("#include <utility>")
    lines.append("")
    lines.append("namespace OpenMagnetics {")
    lines.append("")
    lines.append("static const std::unordered_map<size_t, std::vector<std::pair<float,float>>> CCI_DATA = {")

    for n, fpath in entries:
        coords = []
        with open(fpath) as f:
            for line in f:
                parts = line.split()
                if len(parts) < 3:
                    continue
                try:
                    x = float(parts[1])
                    y = float(parts[2])
                    coords.append((x, y))
                except ValueError:
                    continue
        if not coords:
            continue

        pair_strs = ", ".join(f"{{{x:.8f}f,{y:.8f}f}}" for x, y in coords)
        lines.append(f"    {{{n}, {{{pair_strs}}}}},")

    lines.append("};")
    lines.append("")
    lines.append("const std::vector<std::pair<float,float>>* get_cci_coordinates(size_t n) {")
    lines.append("    auto it = CCI_DATA.find(n);")
    lines.append("    if (it == CCI_DATA.end()) return nullptr;")
    lines.append("    return &it->second;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace OpenMagnetics")
    lines.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Written: {out_path}")

if __name__ == "__main__":
    main()
