#!/usr/bin/env python3
"""
Generate src/support/CciCoordinatesData.cpp from cci_coords text files.
Only embeds N <= MAX_STRANDS; larger N falls back to the spiral algorithm.

Writes the coordinate data as a flat `const float[]` array at namespace scope
so it is emitted into the `.rodata` section of the wasm binary, NOT into a
single giant initializer function. A prior implementation emitted one huge
std::unordered_map initializer-list, which at max_strands=1000 compiled into
a ~8.3 MB startup function that exceeded Chromium's 7.6 MB per-function limit
and broke WASM instantiation in browsers. Flat arrays keep the data payload
out of any function body.

Lookup is O(1) via an offset table keyed by N. Result is cached in a small
unordered_map on first access so callers that rely on a stable
`const std::vector<...>*` address get the same pointer every time.
"""
import os
import sys

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <cci_coords_dir> <output_cpp>")
        sys.exit(1)

    cci_dir = sys.argv[1]
    out_path = sys.argv[2]
    max_strands = 1000

    coordinates_dir = os.path.join(cci_dir, "coordinates")
    if not os.path.isdir(coordinates_dir):
        print(f"ERROR: directory not found: {coordinates_dir}")
        sys.exit(1)

    # Collect files, sorted by N
    entries = []
    for fname in os.listdir(coordinates_dir):
        if not fname.startswith("cci") or not fname.endswith(".txt"):
            continue
        try:
            n = int(fname[3:-4])
        except ValueError:
            continue
        if n <= max_strands:
            entries.append((n, os.path.join(coordinates_dir, fname)))
    entries.sort(key=lambda e: e[0])

    # Read coords per N, keeping the mapping sparse (some N values may be missing).
    # Emit a flat float array and an index that maps each present N to its
    # (offset, count) pair.
    all_coords = []          # list[tuple[float, float]] — contiguous
    index = []               # list[tuple[N, offset, count]]

    for n, fpath in entries:
        coords = []
        with open(fpath) as f:
            for line in f:
                parts = line.split()
                if len(parts) < 3:
                    continue
                try:
                    coords.append((float(parts[1]), float(parts[2])))
                except ValueError:
                    continue
        if not coords:
            continue
        index.append((n, len(all_coords), len(coords)))
        all_coords.extend(coords)

    print(f"Embedding {len(index)} cci coordinate sets "
          f"(N up to {max_strands}, {len(all_coords)} coordinate pairs total)")

    lines = []
    w = lines.append
    w("// Auto-generated by scripts/generate_cci_data.py — do not edit.")
    w("//")
    w("// Data is laid out as flat arrays at namespace scope so the compiler")
    w("// places them in .rodata rather than emitting an initializer function.")
    w("// A prior initializer-list-based version produced a >7 MB startup")
    w("// function that exceeded browser WASM compile limits.")
    w("")
    w('#include "CciCoordinatesData.h"')
    w("#include <unordered_map>")
    w("#include <utility>")
    w("#include <vector>")
    w("#include <mutex>")
    w("")
    w("namespace OpenMagnetics {")
    w("namespace {")
    w("")

    # ---------- flat coordinate array ----------
    # Two floats per pair; emit several per line for readability but nothing
    # heavy — the compiler only cares that this is a single aggregate init.
    w(f"constexpr std::size_t kCoordCount = {len(all_coords)};")
    w("constexpr float kCciCoords[kCoordCount * 2] = {")
    PER_LINE = 8
    for i in range(0, len(all_coords), PER_LINE):
        chunk = all_coords[i : i + PER_LINE]
        flat = ", ".join(f"{x:.8f}f, {y:.8f}f" for x, y in chunk)
        w(f"    {flat},")
    w("};")
    w("")

    # ---------- index table ----------
    w("struct CciEntry { std::size_t n; std::size_t offset; std::size_t count; };")
    w(f"constexpr std::size_t kEntryCount = {len(index)};")
    w("constexpr CciEntry kCciIndex[kEntryCount] = {")
    PER_LINE = 6
    for i in range(0, len(index), PER_LINE):
        chunk = index[i : i + PER_LINE]
        flat = ", ".join(f"{{{n}, {off}, {cnt}}}" for n, off, cnt in chunk)
        w(f"    {flat},")
    w("};")
    w("")

    # ---------- lazy cache ----------
    w("using Vec = std::vector<std::pair<float,float>>;")
    w("std::unordered_map<std::size_t, Vec> g_cache;")
    w("std::mutex g_cache_mutex;")
    w("")

    # ---------- lookup helper that builds + caches on demand ----------
    w("const Vec* build_from_index(std::size_t n) {")
    w("    // Linear scan kept for simplicity — kEntryCount ≤ 1000 and callers")
    w("    // hit the cache after the first call per N.")
    w("    for (std::size_t i = 0; i < kEntryCount; ++i) {")
    w("        if (kCciIndex[i].n != n) continue;")
    w("        Vec v;")
    w("        v.reserve(kCciIndex[i].count);")
    w("        const float* p = kCciCoords + kCciIndex[i].offset * 2;")
    w("        for (std::size_t j = 0; j < kCciIndex[i].count; ++j) {")
    w("            v.emplace_back(p[2 * j], p[2 * j + 1]);")
    w("        }")
    w("        auto [it, _] = g_cache.emplace(n, std::move(v));")
    w("        return &it->second;")
    w("    }")
    w("    return nullptr;")
    w("}")
    w("")
    w("} // namespace")
    w("")
    w("const std::vector<std::pair<float,float>>* get_cci_coordinates(std::size_t n) {")
    w("    std::lock_guard<std::mutex> lock(g_cache_mutex);")
    w("    auto it = g_cache.find(n);")
    w("    if (it != g_cache.end()) return &it->second;")
    w("    return build_from_index(n);")
    w("}")
    w("")
    w("} // namespace OpenMagnetics")
    w("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Written: {out_path}")

if __name__ == "__main__":
    main()
