#include "converter_models/CommonModeChoke.h"
#include "physical_models/MagnetizingInductance.h"
#include "physical_models/WindingOhmicLosses.h"
#include "support/Utils.h"
#include <cfloat>
#include <cmath>
#include <numbers>
#include <sstream>
#include <algorithm>
#include "support/Exceptions.h"

namespace OpenMagnetics {

// ═══════════════════════════════════════════════════════════════════════
// Static helpers
// ═══════════════════════════════════════════════════════════════════════

double CommonModeChoke::impedanceToInductance(double impedance_Ohms, double frequency_Hz) {
    // |Z_L| = 2πf·L  →  L = Z / (2πf)
    return impedance_Ohms / (2.0 * M_PI * frequency_Hz);
}

double CommonModeChoke::inductanceToImpedance(double inductance_H, double frequency_Hz) {
    return 2.0 * M_PI * frequency_Hz * inductance_H;
}

double CommonModeChoke::insertionLossToImpedance(double insertionLoss_dB, double lineImpedance_Ohms) {
    // Single-stage CM low-pass:
    //   IL(dB) ≈ 20·log10(Z_cm/Z_LISN + 1)
    //   → Z_cm = Z_LISN · (10^(IL/20) − 1)
    double linearFactor = std::pow(10.0, insertionLoss_dB / 20.0) - 1.0;
    return lineImpedance_Ohms * linearFactor;
}

std::vector<std::string> CommonModeChoke::windingNames(int numWindings) {
    switch (numWindings) {
        case 2:  return {"Line", "Neutral"};
        case 3:  return {"Phase A", "Phase B", "Phase C"};
        case 4:  return {"Phase A", "Phase B", "Phase C", "Neutral"};
        default: {
            std::vector<std::string> names;
            for (int i = 0; i < numWindings; ++i)
                names.push_back("Winding " + std::to_string(i + 1));
            return names;
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════
// Static helper: noise-estimation → required CM impedance
// ═══════════════════════════════════════════════════════════════════════

double CommonModeChoke::noiseParamsToImpedance(double parasiticCap_pF,
                                    double dvdt_V_ns,
                                    double lineImpedance_Ohms,
                                    double safetyMargin_dB,
                                    double testFrequency_Hz,
                                    double limit_dBuV) {
    // CM current generated by switching transients (simplified):
    //   I_cm = C_parasitic × dV/dt
    double Icm_A      = (parasiticCap_pF * 1e-12) * (dvdt_V_ns * 1e9);
    // CM voltage noise across half of LISN impedance:
    double Vnoise_V   = Icm_A * (lineImpedance_Ohms / 2.0);
    // Convert to dBµV (CISPR reference: 1 µV)
    double Vnoise_dBuV = 20.0 * std::log10(std::max(Vnoise_V, 1e-9) / 1e-6);
    double atten_dB   = std::max(0.0, Vnoise_dBuV - limit_dBuV + safetyMargin_dB);
    // Required CM impedance at the test frequency
    double Zcm        = (lineImpedance_Ohms / 2.0) * std::pow(10.0, atten_dB / 20.0);
    return Zcm;
}

double CommonModeChoke::limitForRegulatoryStandard(const std::string& name) {
    // Quasi-peak conducted-emissions limits at 150 kHz (dBµV).
    // CISPR 32 Class A / FCC Part 15 Class A (industrial): 79 dBµV
    // CISPR 32 Class B / FCC Part 15 Class B (residential): 66 dBµV
    if (name == "CISPR 32 Class A"    ) return 79.0;
    if (name == "CISPR 32 Class B"    ) return 66.0;
    if (name == "FCC Part 15 Class A" ) return 79.0;
    if (name == "FCC Part 15 Class B" ) return 66.0;
    return 66.0;  // Default to the tightest common limit
}

// ═══════════════════════════════════════════════════════════════════════
// Constructor
// ═══════════════════════════════════════════════════════════════════════

CommonModeChoke::CommonModeChoke(const json& j) : Topology(j) {
    operatingVoltage    = j.at("operatingVoltage").get<DimensionWithTolerance>();
    operatingCurrent    = j.at("operatingCurrent").get<double>();
    lineFrequency       = j.at("lineFrequency").get<double>();
    ambientTemperature  = j.at("ambientTemperature").get<double>();

    lineImpedance            = j.value("lineImpedance",            50.0);
    maximumDcResistance      = j.value("maximumDcResistance",       0.0);
    maximumLeakageInductance = j.value("maximumLeakageInductance",  0.0);
    numberOfWindings         = j.value("numberOfWindings",           2);

    // ── Parse minimumImpedance ──────────────────────────────────────
    if (j.contains("minimumImpedance")) {
        for (const auto& item : j.at("minimumImpedance")) {
            minimumImpedance.push_back({
                item.at("frequency").get<double>(),
                item.at("impedance").get<double>()
            });
        }
    }

    // ── Parse targetInsertionLoss and convert to impedance points ───
    if (j.contains("targetInsertionLoss")) {
        for (const auto& item : j.at("targetInsertionLoss")) {
            double freq = item.at("frequency").get<double>();
            double il   = item.at("insertionLoss").get<double>();
            targetInsertionLoss.push_back({freq, il});
            minimumImpedance.push_back({
                freq,
                insertionLossToImpedance(il, lineImpedance)
            });
        }
    }

    // ── Parse noise-estimation params ─────────────────────────────
    // Two distinct effects:
    //   (A) they define the physical CM-excitation amplitude for the
    //       operating point (I_cm = C·dV/dt) — used in every spec mode,
    //       so analytical and simulated always see the same excitation;
    //   (B) when the user hasn't specified an explicit impedance or
    //       insertion-loss requirement, we synthesise one from the noise
    //       level and the regulatory limit — so noise-estimation mode
    //       still yields a sized CMC.
    if (j.contains("parasiticCap_pF") &&
        j.contains("dvdt_V_ns")       &&
        j["parasiticCap_pF"].get<double>() > 0 &&
        j["dvdt_V_ns"].get<double>()   > 0) {

        parasiticCap_pF = j["parasiticCap_pF"].get<double>();
        dvdt_V_ns       = j["dvdt_V_ns"].get<double>();
        safetyMargin_dB = j.value("safetyMargin_dB", 6.0);

        // Only synthesise an impedance point if the user has provided
        // no other spec. Otherwise we would silently override their
        // explicit requirement.
        if (minimumImpedance.empty() && targetInsertionLoss.empty()) {
            const double limit_dBuV = limitForRegulatoryStandard(
                j.value("regulatoryStandard", std::string("CISPR 32 Class B")));
            const double testFreq_Hz = 150e3;
            double Zcm = noiseParamsToImpedance(
                parasiticCap_pF, dvdt_V_ns, lineImpedance, safetyMargin_dB, testFreq_Hz, limit_dBuV);

            minimumImpedance.push_back({ testFreq_Hz, Zcm });
        }
    }

    // ── Compute required inductance from all impedance points ───────
    // L = Z / (2πf) for each point; take the maximum (most demanding)
    computedInductance = 0.0;
    for (const auto& pt : minimumImpedance) {
        double L = impedanceToInductance(pt.impedance, pt.frequency);
        if (L > computedInductance) {
            computedInductance = L;
            dominantFrequency  = pt.frequency;
            dominantImpedance  = pt.impedance;
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════
// AdvancedCommonModeChoke constructor
// ═══════════════════════════════════════════════════════════════════════

AdvancedCommonModeChoke::AdvancedCommonModeChoke(const json& j) : CommonModeChoke(j) {
    desiredInductance = j.at("desiredInductance").get<double>();
    designFrequency   = j.value("designFrequency", 150e3);
    // Seed the operating-point frequency from designFrequency so the core sees
    // excitation at a physically meaningful CMC-band frequency, not lineFrequency.
    set_dominant_frequency(designFrequency);
}

// ═══════════════════════════════════════════════════════════════════════
// run_checks
// ═══════════════════════════════════════════════════════════════════════

bool CommonModeChoke::run_checks(bool assert) {
    if (minimumImpedance.empty()) {
        if (!assert) return false;
        throw InvalidInputException(
            ErrorCode::MISSING_DATA,
            "CMC: at least one impedance requirement must be provided");
    }
    if (operatingCurrent <= 0) {
        if (!assert) return false;
        throw InvalidInputException(
            ErrorCode::INVALID_INPUT,
            "CMC: operatingCurrent must be > 0");
    }
    if (lineFrequency <= 0) {
        if (!assert) return false;
        throw InvalidInputException(
            ErrorCode::INVALID_INPUT,
            "CMC: lineFrequency must be > 0");
    }
    for (const auto& pt : minimumImpedance) {
        if (pt.frequency <= 0 || pt.impedance <= 0) {
            if (!assert) return false;
            throw InvalidInputException(
                ErrorCode::INVALID_INPUT,
                "CMC: impedance point frequency and value must be > 0");
        }
    }
    if (numberOfWindings < 2 || numberOfWindings > 4) {
        if (!assert) return false;
        throw InvalidInputException(
            ErrorCode::INVALID_INPUT,
            "CMC: numberOfWindings must be 2, 3, or 4");
    }
    return true;
}

// ═══════════════════════════════════════════════════════════════════════
// process_design_requirements
// ═══════════════════════════════════════════════════════════════════════

DesignRequirements CommonModeChoke::process_design_requirements() {
    DesignRequirements designRequirements;

    // ── Application / sub-application flags ─────────────────────────
    // Downstream advisers key off these to specialise their behaviour:
    //   - CoreAdviser restricts shapes to TOROIDAL
    //   - CoreMaterial filter favours high-µ, lossy CM materials (MnZn, NC)
    //   - CoilAdviser lays out a bifilar/paired winding
    //   - MagneticFilterLeakageInductance scores tight coupling higher
    // Without these tags, the output is designed like a generic transformer.
    designRequirements.set_application(Application::INTERFERENCE_SUPPRESSION);
    designRequirements.set_sub_application(SubApplication::COMMON_MODE_NOISE_FILTERING);

    // ── Turns ratios: all 1:1 ───────────────────────────────────────
    // A CMC has N identical windings on the same core → every ratio = 1.0
    // There are (numberOfWindings - 1) ratios, same convention as Buck/LLC.
    designRequirements.get_mutable_turns_ratios().clear();
    for (int i = 1; i < numberOfWindings; ++i) {
        DimensionWithTolerance ratio;
        ratio.set_nominal(1.0);
        designRequirements.get_mutable_turns_ratios().push_back(ratio);
    }

    // ── Magnetizing inductance = CM inductance ─────────────────────
    // set_minimum so the core/winding solver treats it as a lower bound
    DimensionWithTolerance lmSpec;
    lmSpec.set_minimum(roundFloat(computedInductance, 10));
    designRequirements.set_magnetizing_inductance(lmSpec);

    // ── Minimum impedance spec ─────────────────────────────────────
    // CoreAdviser::add_ferrite_materials_by_impedance scores materials by
    // complex permeability at each impedance-spec frequency — so it needs
    // the points in the DesignRequirements, not just the stash of {freq,Z}
    // we kept as a member. Build the MAS schema version here.
    if (!minimumImpedance.empty()) {
        // Use MAS:: types explicitly — CommonModeChoke has a local
        // ImpedancePoint struct that would otherwise shadow the MAS schema.
        std::vector<MAS::ImpedanceAtFrequency> impedancePoints;
        for (const auto& pt : minimumImpedance) {
            MAS::ImpedanceAtFrequency p;
            p.set_frequency(pt.frequency);
            MAS::ImpedancePoint mag;
            mag.set_magnitude(pt.impedance);
            p.set_impedance(mag);
            impedancePoints.push_back(p);
        }
        designRequirements.set_minimum_impedance(impedancePoints);
    }

    // ── Isolation sides ────────────────────────────────────────────
    // All windings are on the same magnetic core and typically on the
    // same isolation side in a CM choke (no primary/secondary distinction).
    std::vector<IsolationSide> sides;
    for (int i = 0; i < numberOfWindings; ++i) {
        sides.push_back(get_isolation_side_from_index(0)); // all "primary"
    }
    designRequirements.set_isolation_sides(sides);

    return designRequirements;
}

// ═══════════════════════════════════════════════════════════════════════
// process_operating_points(turnsRatios, magnetizingInductance)
//
// The magnetic core of a CMC only sees the common-mode excitation.
// We model it as a small sinusoidal CM current at the dominant frequency
// (the frequency of the hardest impedance requirement).
// The winding RMS current for copper losses equals the full line current.
// ═══════════════════════════════════════════════════════════════════════

std::vector<OperatingPoint> CommonModeChoke::process_operating_points(
    const std::vector<double>& /*turnsRatios*/,
    double magnetizingInductance)
{
    // Frequency at which the core is excited (worst-case impedance point)
    double excFreq = (dominantFrequency > 0) ? dominantFrequency : lineFrequency;

    // CM current amplitude.
    // Preferred estimate: I_cm = C_parasitic · dV/dt (the physical CM current
    // injected by the switching node through chassis capacitance). Only
    // available in noise-estimation spec mode, where the frontend sends both.
    // Fallback: a representative CM current independent of line load current.
    // CM noise comes from switch-node parasitics (C·dV/dt), not from the
    // mains load, so scaling the fallback with operatingCurrent (the old
    // "1 % of line current" rule) overstated noise on high-current CMCs and
    // pushed the modelled core flux toward saturation for no physical reason.
    // 100 mA ≈ 20 pF × 5 V/ns — a moderate silicon SMPS into a small chassis
    // parasitic, representative of the AC current the core actually sees
    // after any Y-cap upstream of the CMC. Users who want a stricter model
    // should supply parasiticCap_pF + dvdt_V_ns explicitly.
    double iCmPeak;
    if (parasiticCap_pF > 0.0 && dvdt_V_ns > 0.0) {
        // I_cm = (pF · 1e-12) · (V/ns · 1e9) = pF · V/ns · 1e-3  (amps)
        iCmPeak = parasiticCap_pF * dvdt_V_ns * 1e-3;
    } else {
        iCmPeak = 0.1;
    }

    // CM voltage across the inductance: V = L · ω · I_cm_peak
    double omega      = 2.0 * M_PI * excFreq;
    double vCmPeak    = magnetizingInductance * omega * iCmPeak;

    auto names = windingNames(numberOfWindings);

    OperatingPoint operatingPoint;

    for (int w = 0; w < numberOfWindings; ++w) {
        // ── Current waveform ───────────────────────────────────────
        // Every winding gets the SAME waveform: CM ripple at excFreq
        // riding on the line-current DC bias. Identical waveforms are
        // a precondition for Inputs::can_be_common_mode_choke — once
        // it fires, MagnetizingInductance calls
        // get_common_mode_choke_magnetizing_current which drops the DC
        // bias (DM part that cancels in the core) and keeps only the
        // AC ripple as the flux-driving magnetizing current. This is
        // how the CMC path avoids the "5 A × N turns of flux" false
        // saturation — see Inputs.cpp:781.
        Waveform currentWaveform = Inputs::create_waveform(
            WaveformLabel::SINUSOIDAL,
            iCmPeak * 2.0,               // peak-to-peak of CM ripple
            excFreq,
            0.5,                         // duty cycle (unused for sinusoidal)
            operatingCurrent,            // DC offset = nominal line current
            0                            // phase
        );

        // ── Voltage waveform ───────────────────────────────────────
        // Sinusoidal CM voltage induced by the CM inductance
        Waveform voltageWaveform = Inputs::create_waveform(
            WaveformLabel::SINUSOIDAL,
            vCmPeak * 2.0,
            excFreq,
            0.5,
            0.0,  // no DC voltage offset across the CM inductance
            0
        );

        auto excitation = complete_excitation(
            currentWaveform, voltageWaveform, excFreq, names[w]);

        operatingPoint.get_mutable_excitations_per_winding().push_back(excitation);
    }

    OperatingConditions conditions;
    conditions.set_ambient_temperature(ambientTemperature);
    conditions.set_cooling(std::nullopt);
    operatingPoint.set_conditions(conditions);
    operatingPoint.set_name("Nominal");

    return {operatingPoint};
}

// ═══════════════════════════════════════════════════════════════════════
// process_operating_points(Magnetic)
// Calculates Lm from the physical core + coil, then delegates.
// ═══════════════════════════════════════════════════════════════════════

std::vector<OperatingPoint> CommonModeChoke::process_operating_points(Magnetic magnetic) {
    run_checks(_assertErrors);

    auto& settings = Settings::GetInstance();
    MagnetizingInductance magIndModel(settings.get_reluctance_model());
    double Lm = magIndModel
        .calculate_inductance_from_number_turns_and_gapping(
            magnetic.get_mutable_core(),
            magnetic.get_mutable_coil())
        .get_magnetizing_inductance()
        .get_nominal()
        .value();

    std::vector<double> turnsRatios = magnetic.get_turns_ratios();
    return process_operating_points(turnsRatios, Lm);
}

// ═══════════════════════════════════════════════════════════════════════
// AdvancedCommonModeChoke::process
// Mirrors AdvancedBuck::process exactly:
//   1. run_checks
//   2. process_design_requirements  (base computes L from impedance table)
//   3. Override magnetizingInductance with user-specified desiredInductance
//   4. process_operating_points with the overridden value
//   5. Prune harmonics (same call as Topology::process uses)
//   6. Return populated Inputs
// ═══════════════════════════════════════════════════════════════════════

Inputs AdvancedCommonModeChoke::process() {
    CommonModeChoke::run_checks(_assertErrors);

    Inputs inputs;

    auto designRequirements = CommonModeChoke::process_design_requirements();

    // Override with user-supplied inductance
    DimensionWithTolerance lmUser;
    lmUser.set_nominal(roundFloat(desiredInductance, 10));
    designRequirements.set_magnetizing_inductance(lmUser);

    inputs.set_design_requirements(designRequirements);

    std::vector<double> turnsRatios;
    for (const auto& tr : designRequirements.get_turns_ratios())
        turnsRatios.push_back(resolve_dimensional_values(tr));

    auto operatingPoints = CommonModeChoke::process_operating_points(turnsRatios, desiredInductance);

    // Prune harmonics — same step used in Topology::process()
    for (auto& op : operatingPoints)
        op = Inputs::prune_harmonics(op, Defaults().harmonicAmplitudeThreshold);

    for (auto& op : operatingPoints)
        inputs.get_mutable_operating_points().push_back(op);

    return inputs;
}

// ═══════════════════════════════════════════════════════════════════════
// Ngspice simulation methods (from original CommonModeChoke)
// ═══════════════════════════════════════════════════════════════════════

std::string CommonModeChoke::generate_ngspice_circuit(double inductance, double frequency) {
    int numWindings = get_number_of_windings();

    std::ostringstream circuit;
    double period = 1.0 / frequency;

    // Simulation parameters
    int numPeriods = 20;  // Simulate 20 periods for settling
    double simTime = numPeriods * period;
    double stepTime = period / 100;  // 100 points per period

    circuit << "* Common Mode Choke EMI Test Circuit - LISN Configuration\n";
    circuit << "* Generated by OpenMagnetics\n";
    circuit << "* Configuration: " << (numWindings == 2 ? "Single Phase" :
                                       (numWindings == 3 ? "Three Phase" : "Three Phase + Neutral")) << "\n";
    circuit << "* Test frequency: " << (frequency / 1e3) << " kHz\n";
    circuit << "* Inductance per winding: " << (inductance * 1e6) << " uH\n\n";

    // Common mode noise source (represents switching converter noise)
    // Connected to ground, couples into both lines equally
    circuit << "* Common Mode Noise Source (switching noise)\n";
    circuit << "Vcm_noise cm_src 0 SIN(0 1 " << frequency << ")\n\n";

    // Noise coupling capacitors (CM noise couples to both lines)
    circuit << "* CM Noise Coupling (parasitic capacitance to ground)\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << "Ccm" << w << " cm_src cmc_in" << w << " 100p\n";
    }
    circuit << "\n";

    // CMC coupled inductors
    // Windings are wound in the same direction - CM currents add, DM currents cancel
    circuit << "* Common Mode Choke\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << "Lcmc" << w << " cmc_in" << w << " cmc_out" << w << " "
                << std::scientific << inductance << std::fixed << "\n";
    }

    // Couple all windings together (perfect coupling for ideal CMC)
    circuit << "\n* CMC Coupling (k ~ 1 for tight coupling)\n";
    for (int i = 0; i < numWindings; ++i) {
        for (int j = i + 1; j < numWindings; ++j) {
            circuit << "K" << i << "_" << j << " Lcmc" << i << " Lcmc" << j << " 0.99\n";
        }
    }
    circuit << "\n";

    // Simplified LISN per CISPR 16
    // Each line has: Series L (50µH) + parallel RC to ground
    circuit << "* LISN Network (simplified CISPR 16)\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << "* Line " << w << " LISN\n";
        circuit << "Llisn" << w << " cmc_out" << w << " lisn_mid" << w << " 50u\n";
        circuit << "Clisn" << w << " lisn_mid" << w << " 0 1u\n";
        circuit << "Rlisn" << w << " lisn_mid" << w << " lisn_out" << w << " 5\n";
    }
    circuit << "\n";

    // 50Ω measurement resistors (standard EMI receiver input impedance)
    circuit << "* 50Ohm Measurement Point\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << "Rmeas" << w << " lisn_out" << w << " 0 50\n";
    }
    circuit << "\n";

    // Current sense resistors for waveform extraction
    circuit << "* Current Sense\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << "Vsense" << w << " cmc_in" << w << " cmc_in" << w << "_sense 0\n";
    }
    circuit << "\n";

    // AC load (represents the EUT - Equipment Under Test)
    circuit << "* AC Load (EUT)\n";
    double loadResistance = resolve_dimensional_values(operatingVoltage) / operatingCurrent;
    if (numWindings == 2) {
        circuit << "Rload cmc_in0_sense cmc_in1_sense " << loadResistance << "\n";
    } else {
        // Delta-connected load for three-phase
        for (int w = 0; w < 3; ++w) {
            int next = (w + 1) % 3;
            circuit << "Rload" << w << " cmc_in" << w << "_sense cmc_in" << next << "_sense "
                    << (loadResistance * 3) << "\n";
        }
    }
    circuit << "\n";

    // Transient Analysis
    circuit << "* Transient Analysis\n";
    circuit << ".tran " << std::scientific << stepTime << " " << simTime << std::fixed << "\n\n";

    // Save signals
    circuit << "* Output signals\n";
    circuit << ".save v(cm_src)";
    for (int w = 0; w < numWindings; ++w) {
        circuit << " v(lisn_out" << w << ") i(Vsense" << w << ")";
    }
    circuit << "\n\n";

    // Options
    circuit << ".options RELTOL=0.001 ABSTOL=1e-12 VNTOL=1e-9\n\n";

    circuit << ".end\n";

    return circuit.str();
}

std::vector<CmcSimulationWaveforms> CommonModeChoke::simulate_and_extract_waveforms(
    double inductance,
    const std::vector<double>& frequencies) {

    std::vector<CmcSimulationWaveforms> results;

    NgspiceRunner runner;
    if (!runner.is_available()) {
        throw std::runtime_error("ngspice is not available for CMC simulation");
    }

    for (double frequency : frequencies) {
        std::string netlist = generate_ngspice_circuit(inductance, frequency);

        SimulationConfig config;
        config.frequency = frequency;
        config.keepTempFiles = false;
        config.extractOnePeriod = false;

        auto simResult = runner.run_simulation(netlist, config);

        if (!simResult.success) {
            continue;  // Skip failed simulations
        }

        CmcSimulationWaveforms waveforms;
        waveforms.frequency = frequency;
        waveforms.operatingPointName = "CMC_" + std::to_string(static_cast<int>(frequency / 1000)) + "kHz";

        // Extract waveforms from simulation result
        for (size_t i = 0; i < simResult.waveformNames.size(); ++i) {
            const auto& name = simResult.waveformNames[i];
            const auto& wf = simResult.waveforms[i];

            if (name == "cm_src") {
                waveforms.inputVoltage = wf.get_data();
                waveforms.time = wf.get_time().value_or(std::vector<double>());
            } else if (name.find("lisn_out") != std::string::npos) {
                waveforms.lisnVoltage = wf.get_data();
            } else if (name.find("vsense") != std::string::npos) {
                waveforms.windingCurrents.push_back(wf.get_data());
            }
        }

        // Calculate theoretical impedance: Z = 2*pi*f*L
        waveforms.theoreticalImpedance = 2.0 * M_PI * frequency * inductance;

        // Calculate CM attenuation (dB) = 20 * log10(Vin / Vout)
        if (!waveforms.inputVoltage.empty() && !waveforms.lisnVoltage.empty()) {
            double vinPeak = *std::max_element(waveforms.inputVoltage.begin(), waveforms.inputVoltage.end());
            double voutPeak = *std::max_element(waveforms.lisnVoltage.begin(), waveforms.lisnVoltage.end());
            if (voutPeak > 0 && vinPeak > 0) {
                waveforms.commonModeAttenuation = 20.0 * std::log10(vinPeak / voutPeak);
            }
        }

        // Calculate actual impedance from voltage/current (Z = V/I)
        // The CM current is the sum of all winding currents
        if (!waveforms.inputVoltage.empty() && !waveforms.windingCurrents.empty()) {
            double vinPeak = *std::max_element(waveforms.inputVoltage.begin(), waveforms.inputVoltage.end());

            // Sum CM currents from all windings
            double totalCmCurrentPeak = 0;
            for (const auto& windingCurrent : waveforms.windingCurrents) {
                if (!windingCurrent.empty()) {
                    double iPeak = *std::max_element(windingCurrent.begin(), windingCurrent.end());
                    totalCmCurrentPeak += iPeak;
                }
            }

            // Z = V / I (for CM path, all currents flow in same direction)
            if (totalCmCurrentPeak > 1e-12) {
                waveforms.commonModeImpedance = vinPeak / totalCmCurrentPeak;
            } else {
                // If current is negligible, use theoretical value
                waveforms.commonModeImpedance = waveforms.theoreticalImpedance;
            }
        } else {
            waveforms.commonModeImpedance = waveforms.theoreticalImpedance;
        }

        results.push_back(waveforms);
    }

    return results;
}

std::vector<OperatingPoint> CommonModeChoke::simulate_and_extract_operating_points(double inductance) {
    std::vector<OperatingPoint> operatingPoints;

    // Get frequencies from minimum impedance requirements
    std::vector<double> frequencies;
    for (const auto& pt : minimumImpedance) {
        frequencies.push_back(pt.frequency);
    }

    if (frequencies.empty()) {
        frequencies = {100000, 1000000};  // Default: 100kHz and 1MHz
    }

    auto simWaveforms = simulate_and_extract_waveforms(inductance, frequencies);

    for (const auto& simWf : simWaveforms) {
        std::vector<OperatingPointExcitation> excitations;

        // Create voltage waveform from inputVoltage
        Waveform voltageWaveform;
        if (!simWf.inputVoltage.empty()) {
            voltageWaveform.set_data(simWf.inputVoltage);
            if (!simWf.time.empty()) {
                voltageWaveform.set_time(simWf.time);
            }
        }

        for (size_t w = 0; w < simWf.windingCurrents.size(); ++w) {
            Waveform currentWaveform;
            currentWaveform.set_data(simWf.windingCurrents[w]);
            if (!simWf.time.empty()) {
                currentWaveform.set_time(simWf.time);
            }

            SignalDescriptor current;
            current.set_waveform(currentWaveform);
            auto sampledWaveform = Inputs::calculate_sampled_waveform(currentWaveform, simWf.frequency);
            current.set_harmonics(Inputs::calculate_harmonics_data(sampledWaveform, simWf.frequency));
            current.set_processed(Inputs::calculate_processed_data(currentWaveform, simWf.frequency, true));

            OperatingPointExcitation excitation;
            excitation.set_current(current);
            excitation.set_frequency(simWf.frequency);

            // Also set voltage if available
            if (!simWf.inputVoltage.empty()) {
                SignalDescriptor voltage;
                voltage.set_waveform(voltageWaveform);
                auto voltageSampled = Inputs::calculate_sampled_waveform(voltageWaveform, simWf.frequency);
                voltage.set_harmonics(Inputs::calculate_harmonics_data(voltageSampled, simWf.frequency));
                voltage.set_processed(Inputs::calculate_processed_data(voltageWaveform, simWf.frequency, true));
                excitation.set_voltage(voltage);
            }

            excitations.push_back(excitation);
        }

        OperatingPoint operatingPoint;
        operatingPoint.set_excitations_per_winding(excitations);
        operatingPoint.get_mutable_conditions().set_ambient_temperature(ambientTemperature);
        operatingPoint.set_name(simWf.operatingPointName);

        operatingPoints.push_back(operatingPoint);
    }

    return operatingPoints;
}

// ═══════════════════════════════════════════════════════════════════════
// Realistic CMC Simulation with Line Signal + Switching Noise
// ═══════════════════════════════════════════════════════════════════════

std::string CommonModeChoke::generate_realistic_cmc_circuit(
    double inductance,
    double parasiticCap_pF_param,
    double dvdt_V_ns_param,
    double lineFrequency_Hz,
    int numberOfPeriods,
    int numberOfSteadyStatePeriods) {

    if (numberOfPeriods < 1) numberOfPeriods = 1;
    if (numberOfSteadyStatePeriods < 0) numberOfSteadyStatePeriods = 0;

    int numWindings = get_number_of_windings();
    std::ostringstream circuit;

    // Excitation frequency: the dominant noise frequency the CMC was designed
    // for (user-specified impedance spec point, default 150 kHz for EN 55032
    // Class B). Both analytical and simulated paths excite at this frequency
    // so their waveforms can be compared directly — industry convention for
    // CMC design wizards (Würth REDEXPERT, Coilcraft Analyzer).
    double excitationFreq = (dominantFrequency > 0.0) ? dominantFrequency : 150e3;

    // CM noise current amplitude: I_cm = C_parasitic · dV/dt
    double cmNoiseCurrent = (parasiticCap_pF_param * 1e-12) * (dvdt_V_ns_param * 1e9);

    // Simulation timing. We integrate over (steady + measurement) periods of
    // the excitation frequency and ask ngspice (via the 4th `.tran` argument
    // tstart) to only emit samples from the steady-state window.
    int totalPeriods = numberOfSteadyStatePeriods + numberOfPeriods;
    double simTime  = double(totalPeriods) / excitationFreq;
    double tStart   = double(numberOfSteadyStatePeriods) / excitationFreq;
    double timeStep = 1.0 / (excitationFreq * 50); // 50 points per excitation period

    circuit << "* CMC Circuit — sinusoidal CM excitation at dominant frequency\n";
    circuit << "* Line Frequency: " << lineFrequency_Hz << " Hz\n";
    circuit << "* Excitation Frequency: " << (excitationFreq / 1e3) << " kHz\n";
    circuit << "* Parasitic Capacitance: " << parasiticCap_pF_param << " pF\n";
    circuit << "* dV/dt: " << dvdt_V_ns_param << " V/ns\n";
    circuit << "* CM Noise Current: " << (cmNoiseCurrent * 1e3) << " mA\n\n";

    // ── Circuit topology (per winding w) ────────────────────────────
    //
    //   gnd ──(Icm_w sine + DC)── src_w ──Vsense_w── cmc_in_w ──Lcmc_w── cmc_out_w ──Rgnd_w── gnd
    //
    // Each winding is driven by its own ideal current source delivering
    // operatingCurrent (DC line current) + cmNoiseCurrent·sin(2π·fd·t).
    // That is precisely the current waveform the analytical path prescribes
    // (process_operating_points line 283), so both paths produce the same
    // per-winding current and the voltage falls out as L·ω·I·cos(ωt).
    //
    // Windings are uncoupled in the simulation: the analytical formula uses
    // the per-winding self-inductance (magnetizingInductance) directly, with
    // no (1+k) factor, so the simulation must do the same or the voltages
    // will disagree by roughly 2× on a tight-coupled CMC.
    //
    // This is the "design-wizard" view — a pedagogical per-winding sine that
    // matches the closed-form model. A separate EMI-spectrum view will model
    // the broadband trapezoidal source with its coupling parasitics.

    circuit << "* Per-winding CM current source (DC line bias + sinusoidal CM ripple)\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << "Icm" << w << " 0 src" << w
                << " SIN(" << operatingCurrent
                << " "    << cmNoiseCurrent
                << " "    << excitationFreq
                << " 0 0 0)\n";
    }
    circuit << "\n";

    // Current sense: 0V voltage source between src_w and cmc_in_w so
    // i(Vsense_w) reads the winding current.
    circuit << "* Current Sense (0V in series)\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << "Vsense" << w << " src" << w << " cmc_in" << w << " 0\n";
    }
    circuit << "\n";

    // CMC windings — uncoupled self-inductance L per winding (see header note)
    circuit << "* Common Mode Choke windings (uncoupled, matches analytical)\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << "Lcmc" << w << " cmc_in" << w << " cmc_out" << w << " "
                << std::scientific << inductance << std::fixed << "\n";
    }
    circuit << "\n";

    // Return path to ground — small resistor so ngspice has a finite solution
    // at DC; at the excitation frequency this is negligible next to jωL.
    circuit << "* Winding return path to ground\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << "Rgnd" << w << " cmc_out" << w << " 0 1u\n";
    }
    circuit << "\n";

    // Transient Analysis (tstart = steady-state window start → clean periods only)
    circuit << "* Transient Analysis\n";
    circuit << ".tran " << std::scientific << timeStep << " " << simTime
            << " " << tStart << std::fixed << "\n\n";

    // Save signals: node voltages at each end of the winding, and winding
    // current via Vsense. Winding voltage = v(cmc_in) − v(cmc_out).
    circuit << "* Output signals\n";
    for (int w = 0; w < numWindings; ++w) {
        circuit << ".save v(cmc_in" << w << ") v(cmc_out" << w << ") i(Vsense" << w << ")\n";
    }
    circuit << "\n";

    // Options
    circuit << ".options RELTOL=0.001 ABSTOL=1e-12 VNTOL=1e-9\n\n";
    circuit << ".end\n";

    return circuit.str();
}

std::vector<OperatingPoint> CommonModeChoke::simulate_realistic_cmc(
    double inductance,
    double parasiticCap_pF_param,
    double dvdt_V_ns_param,
    int numberOfPeriods,
    int numberOfSteadyStatePeriods) {

    std::vector<OperatingPoint> operatingPoints;

    NgspiceRunner runner;
    if (!runner.is_available()) {
        throw std::runtime_error("ngspice is not available for CMC simulation");
    }

    // Excitation frequency: same as analytical path (dominantFrequency). Falls
    // back to the EN 55032 Class B conducted-emissions start point if unset.
    double excitationFreq = (dominantFrequency > 0.0) ? dominantFrequency : 150e3;

    // Generate circuit with sinusoidal CM excitation
    std::string netlist = generate_realistic_cmc_circuit(
        inductance, parasiticCap_pF_param, dvdt_V_ns_param, lineFrequency,
        numberOfPeriods, numberOfSteadyStatePeriods);

    SimulationConfig config;
    config.frequency = excitationFreq;  // one period = 1/excitationFreq
    config.keepTempFiles = false;
    config.extractOnePeriod = false;

    auto simResult = runner.run_simulation(netlist, config);

    if (!simResult.success) {
        throw std::runtime_error("CMC realistic simulation failed: " + simResult.errorMessage);
    }

    int numWindings = get_number_of_windings();
    auto names = windingNames(numWindings);  // Same labels as analytical path

    // Create excitations for each winding
    std::vector<OperatingPointExcitation> excitations;
    for (int w = 0; w < numWindings; ++w) {
        // ngspice output names: voltage is node name, current is component name + "#branch"
        std::string vinName  = "cmc_in"  + std::to_string(w);
        std::string voutName = "cmc_out" + std::to_string(w);
        std::string iName    = "vsense"  + std::to_string(w) + "#branch";

        // Find waveforms for this winding
        std::vector<double> time;
        std::vector<double> vIn;
        std::vector<double> vOut;
        std::vector<double> current;

        for (size_t i = 0; i < simResult.waveformNames.size(); ++i) {
            const auto& name = simResult.waveformNames[i];
            const auto& wf = simResult.waveforms[i];

            if (name == vinName) {
                vIn = wf.get_data();
                time = wf.get_time().value_or(std::vector<double>());
            } else if (name == voutName) {
                vOut = wf.get_data();
            } else if (name == iName) {
                current = wf.get_data();
            }
        }

        // Voltage across the winding: v_in − v_out. The absolute node voltage
        // carries a line-frequency bias that looks like a ramp at switching
        // time-scale; the difference is the induced CM-drive voltage, which is
        // the physically meaningful signal for core-loss calculations.
        std::vector<double> voltage;
        if (vIn.size() == vOut.size()) {
            voltage.reserve(vIn.size());
            for (size_t i = 0; i < vIn.size(); ++i)
                voltage.push_back(vIn[i] - vOut[i]);
        }

        if (!time.empty() && !voltage.empty() && !current.empty()) {
            // Normalize time origin to 0. Ngspice returns samples starting at
            // tStart (the steady-state cut-in), but downstream sampling in
            // Inputs::calculate_sampled_waveform assumes the waveform covers
            // [0, 1/f). Shift by time[0] so one switching period is visible.
            double t0 = time.front();
            if (t0 != 0.0) {
                for (auto& t : time) t -= t0;
            }

            // Create voltage waveform
            Waveform voltageWaveform;
            voltageWaveform.set_data(voltage);
            voltageWaveform.set_time(time);

            // Create current waveform
            Waveform currentWaveform;
            currentWaveform.set_data(current);
            currentWaveform.set_time(time);

            // Build excitation at the dominant impedance frequency — matches
            // analytical path so the two can be compared directly. Winding
            // label comes from the same helper the analytical path uses so
            // the legend in the UI matches across both views.
            auto excitation = Topology::complete_excitation(
                currentWaveform,
                voltageWaveform,
                excitationFreq,
                names[w]);

            excitations.push_back(excitation);
        }
    }

    if (!excitations.empty()) {
        OperatingPoint operatingPoint;
        operatingPoint.set_excitations_per_winding(excitations);
        operatingPoint.get_mutable_conditions().set_ambient_temperature(ambientTemperature);
        operatingPoint.set_name("Simulated");

        operatingPoints.push_back(operatingPoint);
    }

    return operatingPoints;
}

} // namespace OpenMagnetics
