#pragma once
#include <cmath>
#include <vector>
#include <algorithm>

namespace OpenMagnetics {

// =========================================================================
// PwmBridgeSolver — shared analytical kernel for phase-shifted PWM bridge
// converters (PSFB, 3-level PSHB, optionally AHB).
//
// Provides:
//   * compute_duty_cycle_loss     — Sabate 1990 / Andreycak U-136A.
//   * compute_zvs_margin_lagging  — half-bridge or full-bridge ZVS energy
//                                   inequality with user-supplied Coss.
//   * compute_resonant_transition_time — quarter-period of Lk·2·Coss.
//   * SubInterval / build_subintervals — three breakpoints per half-cycle:
//       0  →  t_dcl                    : commutation (duty-cycle loss)
//       t_dcl  →  t_active             : power transfer
//       t_active  →  T/2               : freewheeling
//     Antisymmetric mirror over the second half-cycle.
//
// This is intentionally simpler than the DAB sub-interval propagator because
// PSFB / 3-level PSHB have only three constant-voltage segments per half-
// cycle, not eight (DAB's worst case). The same struct is reused for both
// PSFB and 3LPSHB via the `bus_voltage_factor` parameter (1.0 for PSFB,
// 0.5 for 3LPSHB). Both are full-cycle symmetric so the second half is
// generated by negating the first.
// =========================================================================
namespace PwmBridgeSolver {

/// Duty-cycle loss for a PSFB or 3LPSHB:
///     ΔD = 4·Lk·Io·Fs / (n·Vbus)
/// where Vbus is Vin (PSFB) or Vin/2 (3LPSHB) — pass the appropriate
/// voltage as `Vbus`. Returns ΔD in absolute duty (0..1) units; multiply
/// by Ts/2 to get the time-domain commutation interval.
/// Reference: Sabate et al., "Design considerations for high-voltage
/// high-power full-bridge ZVS-PWM converter," APEC 1990 (Eq. 7); also
/// Andreycak, Unitrode U-136A.
inline double compute_duty_cycle_loss(double Vbus, double Lk, double Io,
                                      double n, double Fs) {
    if (Vbus <= 0 || n <= 0 || Fs <= 0) return 0.0;
    return 4.0 * Lk * Io * Fs / (n * Vbus);
}

/// Effective duty cycle after subtracting duty-cycle loss. Clamped to
/// [0, D_cmd] so a too-large Lk does not produce a negative D_eff.
inline double compute_effective_duty_cycle(double D_cmd, double dcl) {
    double D = D_cmd - dcl;
    if (D < 0.0) D = 0.0;
    if (D > 1.0) D = 1.0;
    return D;
}

/// Lagging-leg ZVS margin (Joules):
///     E_margin = ½·Lk·Ip² − 2·Coss·Vbus²
/// Positive ⇒ ZVS is achieved on the lagging leg; negative ⇒ hard
/// switching. Coss is the per-MOSFET output capacitance (the lagging
/// leg has two devices in parallel during the transition, hence the
/// factor of 2). For a single-leg HB topology the same formula applies
/// with Vbus = Vin (AHB) or Vin/2 (split-cap HB).
inline double compute_zvs_margin_lagging(double Lk, double Ip, double Coss,
                                         double Vbus) {
    double E_inductor = 0.5 * Lk * Ip * Ip;
    double E_caps = 2.0 * Coss * Vbus * Vbus;
    return E_inductor - E_caps;
}

/// Quarter-period of the lagging-leg resonant tank Lk·(2·Coss):
///     t_r = (π/2) · √(Lk · 2·Coss)
/// This is the dead-time required for a complete ZVS transition. If the
/// gate-driver dead-time is shorter, the transition is incomplete and
/// hard switching occurs even with sufficient ZVS energy.
inline double compute_resonant_transition_time(double Lk, double Coss) {
    if (Lk <= 0 || Coss <= 0) return 0.0;
    return (M_PI / 2.0) * std::sqrt(2.0 * Lk * Coss);
}

/// Minimum primary current at the start of the lagging-leg transition for
/// ZVS, derived from ½·Lk·Ip² = 2·Coss·Vbus²:
///     Ip_min = Vbus · √(2·Coss / Lk)
inline double compute_zvs_primary_current_min(double Lk, double Coss,
                                              double Vbus) {
    if (Lk <= 0) return 0.0;
    return Vbus * std::sqrt(2.0 * Coss / Lk);
}

/// Sub-interval descriptor for one segment of the half-cycle. Within the
/// segment `Vp` is constant, the rectifier state is the `is_active` flag,
/// and `t_start..t_end` is in seconds (referenced to t = 0 at the start
/// of the half-cycle).
struct SubInterval {
    double t_start;
    double t_end;
    double Vp;          // primary winding voltage (signed)
    bool   is_active;   // true = power-transfer, false = freewheel/commutation
    bool   is_commutation; // true only during the duty-cycle-loss segment
};

/// Build the three-segment first-half-cycle breakdown for PSFB / 3LPSHB.
/// `D_cmd` is the commanded duty (phase_shift / 180). `dcl_duty` is the
/// duty-cycle loss in the same (0..1) units. `Vbus` is the primary bridge
/// peak voltage. Returns a vector of three intervals covering [0, T/2];
/// the symmetric second half is obtained by negating Vp and shifting time
/// by T/2.
inline std::vector<SubInterval> build_first_half_cycle(double T, double Vbus,
                                                       double D_cmd, double dcl_duty)
{
    double Thalf = 0.5 * T;
    double t_dcl    = std::min(dcl_duty * Thalf, Thalf);
    double t_active = std::min(D_cmd * Thalf,    Thalf);
    if (t_active < t_dcl) t_active = t_dcl;     // ΔD ≥ D_cmd ⇒ no power

    std::vector<SubInterval> segs;
    // Commutation interval: primary already at +Vbus, but rectifier hasn't
    // commutated yet. Output inductor freewheels.
    if (t_dcl > 0) {
        segs.push_back({0.0, t_dcl, Vbus, false, true});
    }
    // Active power-transfer interval.
    if (t_active > t_dcl) {
        segs.push_back({t_dcl, t_active, Vbus, true, false});
    }
    // Freewheeling interval: primary clamped to 0V via same-leg pair.
    if (t_active < Thalf) {
        segs.push_back({t_active, Thalf, 0.0, false, false});
    }
    return segs;
}

}  // namespace PwmBridgeSolver

}  // namespace OpenMagnetics
